### PR TITLE
cpu: aarch64: enable ACL's inner-product for BF16

### LINKED ISSUE #180447: Poor BF16 torch.compile + Freezing perf on AArch64 CPUs
### 🐛 Describe the bug

When you compile and freeze a BF16 model (for weight prepacking) on AArch64, the matmul gets dispatched to oneDNN reference kernels rather than ACL/jit optimized oneDNN kernels. As a result you run 100x slower than eager mode.

This is reproducible with any torch version.
Note: for fp32, we already dispatch to optimized kernels.

```
import torch 

torch._inductor.config.freezing = True

# This dispatches to optimized oneDNN kernels
#dtype = torch.float32

# This dispatches to reference oneDNN kernels -> more than 100x slower than eager 
dtype = torch.bfloat16

def main():
    with torch.no_grad():
        x = torch.rand(size=(1024, 1024), dtype=dtype)
        linear = torch.nn.Linear(1024, 1024).to(dtype).eval()
        # compile and warmup
        linear = torch.compile(linear)
        linear(x)
        print("should have no reorders after this", flush=True)
        for _ in range(10):
            linear(x)
            print("=="*20, flush=True)

if __name__ == "__main__":
    main()
```

cc @jerryzh168 @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @aditew01 @gujinghui @PenghuiCheng @jianyuh @min-jean-cho @yanbing-j @Guobing-Chen @Xia-Weiwen @snadampal @milpuz01 @nikhil-arm @robert-hardwick @nWEIdia @chauhang @penguinwu @voznesenskym @EikanWang @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @kadeng @muchulee8 @amjames @aakhundov @coconutruben @jataylo

### PR DESCRIPTION
**Pull request by fadara01**
# Description

cpu: aarch64: enable ACL's inner-product for BF16

This benchdnn repro with ACL built with https://github.com/ARM-software/ComputeLibrary/pull/1279 now goes to ACL which is > 100x faster:
```
ONEDNN_VERBOSE=all ./tests/benchdnn/benchdnn --ip --mode=C --dir=FWD_I  --bia-dt=bf16  --dt=bf16 mb1024ic1024oc1024
```

This PR + https://github.com/ARM-software/ComputeLibrary/pull/1279 fix: https://github.com/pytorch/pytorch/issues/180447

Fixes # (github issue)

# Checklist

## General

- [ ] Do all unit and benchdnn tests (`make test` and `make test_benchdnn_*`) pass locally for each commit?
- [ ] Have you formatted the code using clang-format?

## Performance improvements

- [ ] Have you submitted performance data that demonstrates performance improvements?

### New features

- [ ] Have you published an RFC for the new feature?
- [ ] Was the RFC approved?
- [ ] Have you added relevant tests?

### Bug fixes

- [ ] Have you included information on how to reproduce the issue (either in a github issue or in this PR)?
- [ ] Have you added relevant regression tests?

## [RFC](https://github.com/uxlfoundation/oneDNN/tree/rfcs) PR

- [ ] Does RFC document follow the [template](https://github.com/uxlfoundation/oneDNN/blob/rfcs/rfcs/template.md#onednn-design-document-rfc)?
- [ ] Have you added a link to the rendered document?

### CODE REVIEW

**Comment by fadara01** [comment]
cc: @jondea @Sqvid

**Comment by aditew01** [comment]
do you need to upgrade ACL version once this is merged? https://github.com/ARM-software/ComputeLibrary/pull/1279

**Comment by fadara01** [comment]
>do you need to upgrade ACL version once this is merged? https://github.com/ARM-software/ComputeLibrary/pull/1279

Nope, I think we can just merge this without updating ACL version  - in this case oneDNN will just bail out a bit later when doing ACL validate.

**Comment by aditew01** [comment]
> Nope, I think we can just merge this without updating ACL version - in this case oneDNN will just bail out a bit later when doing ACL validate.

Yeah, i was referring to this: 
>This benchdnn repro now goes to ACL which is > 100x faster

**Comment by fadara01** [comment]
@aditew01 - I see your point, I updated the description.

**Comment by fadara01** [comment]
I assume we have CI here to test oneDNN main vs ACL main? In which case let's wait for the ACL PR https://github.com/ARM-software/ComputeLibrary/pull/1279 to hit main before we merge this.

File: src/cpu/aarch64/acl_inner_product.cpp [hunk 1]
```diff
@@ -100,11 +100,13 @@ status_t acl_inner_product_fwd_t::pd_t::init(engine_t *engine) {
     const bool is_fp32_ok = expect_data_types(f32, f32, f32, f32, undef)
             && attr()->has_default_values(
                     smask_t::post_ops | smask_t::fpmath_mode, f32);
+    const bool is_bf16_ok = expect_data_types(bf16, bf16, bf16, bf16, undef)
+            && attr()->has_default_values(smask_t::post_ops, bf16);
```
Comment (aditew01) [inline src/cpu/aarch64/acl_inner_product.cpp:104]: I'm not sure if this extra check is needed here / is covered in ACL. 
```suggestion
            && attr()->has_default_values(smask_t::post_ops, bf16) && platform::has_data_type_support(data_type::bf16);
```

**Review by aditew01 — APPROVED** [review]

File: src/cpu/aarch64/acl_inner_product.cpp (hunk 1 above)
Comment (fadara01) [reply src/cpu/aarch64/acl_inner_product.cpp:104]: I'm not sure tbh, I think most of these checks are redundant anyways because the same checks will happen by calls to validate / has_opt_impl across ACL interfaces from CpuFullyConnected all the way to arm_gemm.

We have c6g CI here, we can test this in CI once the ACL PR is merged

**Comment by jondea** [comment]
> I assume we have CI here to test oneDNN main vs ACL main

I don't think we have this currently

**Comment by fadara01** [comment]
>I don't think we have this currently

okay, I'll run the nightly test suite locally with both the oneDNN and ACL PRs.

**Comment by fadara01** [comment]
OK, I built:
- ACL with main + https://github.com/ARM-software/ComputeLibrary/pull/1279 and 
- oneDNN with main + this PR + above ACL build, with `-DDNNL_TEST_SET=NIGHTLY`

then I ran the full nightly suite (246 tests) with `ctest` on Neoverse-V2 and everything passed
```
100% tests passed, 0 tests failed out of 246
```

**Review by jondea — APPROVED** [review]

**Comment by Sqvid** [comment]
@fadara01 If you want this change in the oneDNN 3.12 release then please raise a backport PR.

**Comment by fadara01** [comment]
@Sqvid - I raised this backport PR against 3.12: https://github.com/uxlfoundation/oneDNN/pull/5061
