### PR TITLE
cpu: aarch64: matmul: fix brgemm multidims tag detection

### LINKED ISSUE #2008: brg:sve_256 fails benchdnn accuracy tests
# Summary
`test_benchdnn_modeC_matmul_multidims_cpu` is failing due to `brg:sve_256` on main/v3.6 319a77eb3da6809476dbf0b512ffacfa88238b76

The failing benchdnn calls are
```
> ./tests/benchdnn/benchdnn --matmul --stag=acbd --wtag=acbd --dtag=acbd --attr-fpmath=bf16, 1x16x38x64:105x1x64x38
[23104][DST][1:0:0:0] exp_f32:         -71 exp:         -71 got:        -157 diff:      86 rdiff: 1.21127
[23105][DST][1:0:0:1] exp_f32:          15 exp:          15 got:           8 diff:       7 rdiff:0.466667
[23106][DST][1:0:0:2] exp_f32:         186 exp:         186 got:        -129 diff:     315 rdiff: 1.69355
[23107][DST][1:0:0:3] exp_f32:          -3 exp:          -3 got:        -100 diff:      97 rdiff: 32.3333
[23108][DST][1:0:0:4] exp_f32:          -1 exp:          -1 got:          28 diff:      29 rdiff:      29
[23109][DST][1:0:0:5] exp_f32:         100 exp:         100 got:          40 diff:      60 rdiff:     0.6
[23110][DST][1:0:0:6] exp_f32:          15 exp:          15 got:         -77 diff:      92 rdiff: 6.13333
[23111][DST][1:0:0:7] exp_f32:          95 exp:          95 got:         -44 diff:     139 rdiff: 1.46316
[23112][DST][1:0:0:8] exp_f32:         -62 exp:         -62 got:         106 diff:     168 rdiff: 2.70968
[23113][DST][1:0:0:9] exp_f32:          31 exp:          31 got:         117 diff:      86 rdiff: 2.77419
[COMPARE_STATS][DST]: trh=1e-06 err_max_diff:     815 err_max_rdiff:     435 all_max_diff:     815 all_max_rdiff:     435
0:FAILED (errors:2396156 total:2425920) __REPRO: --matmul --stag=acbd --wtag=acbd --dtag=acbd --attr-fpmath=bf16 1x16x38x64:105x1x64x38
[23104][DST][1:0:0:0] exp_f32:      -15580 exp:      -15580 got:      -34229 diff:   18649 rdiff: 1.19698
[23105][DST][1:0:0:1] exp_f32:        7185 exp:        7185 got:       -1041 diff:    8226 rdiff: 1.14489
[23106][DST][1:0:0:2] exp_f32:       41612 exp:       41612 got:      -27123 diff:   68735 rdiff: 1.65181
[23107][DST][1:0:0:3] exp_f32:        2969 exp:        2969 got:      -15306 diff:   18275 rdiff: 6.15527
[23108][DST][1:0:0:4] exp_f32:        3112 exp:        3112 got:        8814 diff:    5702 rdiff: 1.83226
[23109][DST][1:0:0:5] exp_f32:       16910 exp:       16910 got:       12855 diff:    4055 rdiff:0.239799
[23110][DST][1:0:0:6] exp_f32:        -401 exp:        -401 got:      -12707 diff:   12306 rdiff: 30.6883
[23111][DST][1:0:0:7] exp_f32:       25251 exp:       25251 got:      -10682 diff:   35933 rdiff: 1.42303
[23112][DST][1:0:0:8] exp_f32:      -12964 exp:      -12964 got:       23692 diff:   36656 rdiff: 2.82752
[23113][DST][1:0:0:9] exp_f32:        5708 exp:        5708 got:       24813 diff:   19105 rdiff: 3.34706
[COMPARE_STATS][DST]: trh=1e-06 err_max_diff:  176270 err_max_rdiff:   60963 all_max_diff:  176270 all_max_rdiff:   60963
1:FAILED (errors:2402790 total:2425920) __REPRO: --matmul --stag=acbd --wtag=acbd --dtag=acbd 1x16x38x64:105x1x64x38
tests:2 passed:0 skipped:0 mistrusted:0 unimplemented:0 invalid_arguments:0 failed:2 listed:0
```

Pinging @vineelabhinav @Shreyas-fuj from git blame

# Environment
* CPU: Neoverse-V1 C7g.4xlarge
* OS version: Ubuntu 20.04
* Compiler version: gcc-10
* git hash: 319a77eb3da6809476dbf0b512ffacfa88238b76
* CMake version: 3.16.3
* CMake output log
```
+ cmake -DDNNL_CPU_RUNTIME=OMP -DCMAKE_BUILD_TYPE=Release -DDNNL_BUILD_FOR_CI=ON -DDNNL_WERROR=OFF -DDNNL_TEST_SET=NIGHTLY ..
-- The C compiler identification is GNU 10.5.0
-- The CXX compiler identification is GNU 10.5.0
-- Check for working C compiler: /usr/bin/gcc-10
-- Check for working C compiler: /usr/bin/gcc-10 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/g++-10
-- Check for working CXX compiler: /usr/bin/g++-10 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- DNNL_TARGET_ARCH: AARCH64
-- DNNL_LIBRARY_NAME: dnnl
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found OpenMP_C: -fopenmp (found version "4.5")
-- Found OpenMP_CXX: -fopenmp (found version "4.5")
-- Found OpenMP: TRUE (found version "4.5")
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
-- Could NOT find Doxyrest (missing: DOXYREST_EXECUTABLE)
-- Found PythonInterp: /usr/bin/python2.7 (found suitable version "2.7.18", minimum required is "2.7")
-- Found Sphinx: /usr/bin/sphinx-build (found version "sphinx-build 1.8.5")
-- Found Git: /usr/bin/git (found version "2.25.1")
-- Enabled testing coverage: NIGHTLY
-- Enabled workload: TRAINING
-- Enabled primitives: ALL
-- Enabled primitive CPU ISA: ALL
-- Enabled primitive GPU ISA: ALL
-- Enabled GeMM kernels ISA: ALL
-- Primitive cache is enabled
-- Graph component is enabled
-- Graph compiler backend is disabled.
-- Configuring done
-- Generating done
-- Build files have been written to: oneDNN/build
```

### PR DESCRIPTION
**Pull request by Sqvid**
# Description

This fix for AArch64 is analogous to b646838bc25d3f02ff98e015930ae7461206e15f

Fixes #2008

# Checklist

## General

- [X] Do all unit and benchdnn tests (`make test` and `make test_benchdnn_*`) pass locally for each commit?
- [X] Have you formatted the code using clang-format?

### Bug fixes

- [X] Have you included information on how to reproduce the issue (either in a github issue or in this PR)?
- [X] Have you added relevant regression tests?

### CODE REVIEW

**Comment by Sqvid** [comment]
cc: @jondea, @Ryo-not-rio

**Comment by Sqvid** [comment]
The implementations dispatched to are the same before and after the fix:
```
============================================================
= Implementation statistics (--summary=no-impl to disable) =
============================================================
|         gemm:jit : 5032 (55%)                            |
|    gemm:jit:bf16 : 2308 (25%)                            |
|     gemm:jit:f32 : 1032 (11%)                            |
|         gemm:acl : 638 (7%)                              |
|      brg:sve_256 : 48 (1%)                               |
|    lowp_gemm:acl : 45 (0%)                               |
| lowp_gemm_sq:acl : 11 (0%)                               |
|         jit:int8 : 10 (0%)                               |
============================================================
```

The following four cases fail before:
```
$ ./build/tests/benchdnn/benchdnn --matmul --global-skip-impl='ref,simple' --stag=acbd --wtag=acbd --dtag=acbd --attr-fpmath=,bf16 1x16x38x64:5x1x64x38 2x16x384x384:2x1x384x64
[23104][DST][1:0:0:0] exp_f32:      -20513 exp:      -20513 got:       18725 diff:   39238 rdiff: 1.91284
[23105][DST][1:0:0:1] exp_f32:       -1873 exp:       -1873 got:       15486 diff:   17359 rdiff: 9.26802
[23106][DST][1:0:0:2] exp_f32:       17357 exp:       17357 got:       -7949 diff:   25306 rdiff: 1.45797
[23107][DST][1:0:0:3] exp_f32:      -48673 exp:      -48673 got:       34671 diff:   83344 rdiff: 1.71233
[23108][DST][1:0:0:4] exp_f32:      -10637 exp:      -10637 got:      -31116 diff:   20479 rdiff: 1.92526
[23109][DST][1:0:0:5] exp_f32:       22679 exp:       22679 got:      -13353 diff:   36032 rdiff: 1.58878
[23110][DST][1:0:0:6] exp_f32:         683 exp:         683 got:      -41106 diff:   41789 rdiff: 61.1845                                                                                                                                                              
[23111][DST][1:0:0:7] exp_f32:       32521 exp:       32521 got:        1599 diff:   30922 rdiff:0.950832                                                                                                                                                              
[23112][DST][1:0:0:8] exp_f32:       -2058 exp:       -2058 got:        7822 diff:    9880 rdiff: 4.80078                                                                                                                                                              
[23113][DST][1:0:0:9] exp_f32:       28751 exp:       28751 got:       11390 diff:   17361 rdiff: 0.60384                                                                                                                                                              
[COMPARE_STATS][DST]: trh=0 err_max_diff:  255312 err_max_rdiff:   55232 all_max_diff:  255312 all_max_rdiff:   55232
0:FAILED (errors:92415 total:115520) (20 ms) __REPRO: --matmul --stag=acbd --wtag=acbd --dtag=acbd --skip-impl=ref,simple 1x16x38x64:5x1x64x38
...
============================================================
= Implementation statistics (--summary=no-impl to disable) =
============================================================
| brg:sve_256 : 4 (100%)                                   |
============================================================
===========================================================
= Failed cases summary (--summary=no-failures to disable) =
===========================================================
0:FAILED (errors:92415 total:115520) (20 ms) __REPRO: --matmul --stag=acbd --wtag=acbd --dtag=acbd --skip-impl=ref,simple 1x16x38x64:5x1x64x38
1:FAILED (errors:91524 total:115520) (9 ms) __REPRO: --matmul --stag=acbd --wtag=acbd --dtag=acbd --attr-fpmath=bf16 --skip-impl=ref,simple 1x16x38x64:5x1x64x38
2:FAILED (errors:393214 total:786432) (44 ms) __REPRO: --matmul --stag=acbd --wtag=acbd --dtag=acbd --skip-impl=ref,simple 2x16x384x384:2x1x384x64
3:FAILED (errors:391995 total:786432) (41 ms) __REPRO: --matmul --stag=acbd --wtag=acbd --dtag=acbd --attr-fpmath=bf16 --skip-impl=ref,simple 2x16x384x384:2x1x384x64
============================
tests:4 passed:0 skipped:0 mistrusted:0 unimplemented:0 invalid_arguments:0 failed:4 listed:0
total: 0.12s; create_pd: 0.00s (1%); create_prim: 0.00s (1%); fill: 0.03s (22%); execute: 0.00s (4%); compute_ref: 0.04s (35%); compare: 0.02s (13%);
```

And pass after:
```
$ ./build/tests/benchdnn/benchdnn --matmul --global-skip-impl='ref,simple' --stag=acbd --wtag=acbd --dtag=acbd --attr-fpmath=,bf16 1x16x38x64:5x1x64x38 2x16x384x384:2x1x384x64

0:PASSED (17 ms) __REPRO: --matmul --stag=acbd --wtag=acbd --dtag=acbd --skip-impl=ref,simple 1x16x38x64:5x1x64x38
1:PASSED (10 ms) __REPRO: --matmul --stag=acbd --wtag=acbd --dtag=acbd --attr-fpmath=bf16 --skip-impl=ref,simple 1x16x38x64:5x1x64x38
2:PASSED (42 ms) __REPRO: --matmul --stag=acbd --wtag=acbd --dtag=acbd --skip-impl=ref,simple 2x16x384x384:2x1x384x64
3:PASSED (43 ms) __REPRO: --matmul --stag=acbd --wtag=acbd --dtag=acbd --attr-fpmath=bf16 --skip-impl=ref,simple 2x16x384x384:2x1x384x64
============================================================
= Implementation statistics (--summary=no-impl to disable) =
============================================================
| brg:sve_256 : 4 (100%)                                   |
============================================================
tests:4 passed:4 skipped:0 mistrusted:0 unimplemented:0 invalid_arguments:0 failed:0 listed:0
total: 0.12s; create_pd: 0.00s (0%); create_prim: 0.00s (1%); fill: 0.02s (21%); execute: 0.01s (4%); compute_ref: 0.05s (39%); compare: 0.01s (10%);
```

**Comment by Sqvid** [comment]
Passed nightly with `ctest -R "matmul|brgemm|conv"`

File: src/cpu/aarch64/matmul/brgemm_matmul_utils.cpp [hunk 1]
```diff
@@ -225,13 +223,9 @@ status_t brgemm_matmul_conf_utils_t::set_or_check_B_tag(
...
         // format tensor. This removes the need of allocating a scratchpad for
         // copy_B.
-        if (transposed_tensor_layout_tag == bgmmc.wei_tag) {
-            memory_desc_t B_md_plain;
-            const status_t status
-                    = memory_desc_init_by_tag(B_md_plain, B_md.ndims, B_md.dims,
-                            B_md.data_type, plain_tensor_layout_tag);
-            if (status != status::success) return status;
-            if (B_md_plain == B_md) bgmmc.wei_tag = plain_tensor_layout_tag;
+        if (memory_desc_matches_tag(B_md, transposed_tensor_layout_tag)
```
Comment (jondea) [inline src/cpu/aarch64/matmul/brgemm_matmul_utils.cpp:229]: Can we have a comment here explaining what's going on, and why we make the decision to pick the plain version.

File: src/cpu/aarch64/matmul/brgemm_matmul_utils.cpp [hunk 2]
```diff
@@ -1031,14 +1032,24 @@ void init_aux_values(brgemm_matmul_conf_t &bgmmc,
...
-        bgmmc.copy_A_src_stride = nstl::min(src_d.blocking_desc().strides[0],
-                                          src_stride / factor)
-                * factor;
-        const dim_t bcast_shift_b = bgmmc.src_tag == acbd ? bgmmc.K : bgmmc.M;
+
+    // If src have dimensions equal to 1, multiple tags can be matched so
+    // we need to make sure:
+    // - A_ptr_shift_b is set for acbd and adbc even if bgmmc.src_tag is abcd
+    // - Plain md that matches acbd or adbc does not dispatch into their codepath
+    if (src_d.matches_one_of_tag(acbd, adbc)) {
```
Comment (jondea) [inline src/cpu/aarch64/matmul/brgemm_matmul_utils.cpp]: This returns a `format_tag`, can we make the comparison explict rather than implicitly casting to bool?

File: src/cpu/aarch64/matmul/brgemm_matmul.cpp [hunk 3]
```diff
@@ -1127,11 +1126,15 @@ struct brgemm_matmul_t<isa>::brg_matmul_exec_ctx_t {
     }
 
     // Auxiliary functions for getting offsets with pre-calculated memory
-    // strides for each tensor to get general sulution for all possible
+    // strides for each tensor to get general solution for all possible
```
Comment (jondea) [inline src/cpu/aarch64/matmul/brgemm_matmul.cpp:1129]: Nu, this wus currect befure!

Comment (Sqvid) [reply src/cpu/aarch64/matmul/brgemm_matmul.cpp:1129]: Surry, typu

File: src/cpu/aarch64/matmul/brgemm_matmul_utils.cpp (hunk 2 above)
Comment (Sqvid) [reply src/cpu/aarch64/matmul/brgemm_matmul_utils.cpp]: Done.

File: src/cpu/aarch64/matmul/brgemm_matmul_utils.cpp (hunk 1 above)
Comment (Sqvid) [reply src/cpu/aarch64/matmul/brgemm_matmul_utils.cpp:229]: I have added a more explanatory comment. Is it better?

**Comment by Sqvid** [comment]
> Can we not disambiguate the tag once at the start for each tensor, and continue as before?

I think a lot of `tag`-based logic exists throughout the kernel and I'd rather not mix that simplification in with this change. Going forward it would be better if based our logic on strides and dimensions rather than memory tags.

**Comment by Ryo-not-rio** [comment]
Could we get some perf numbers on c7g?

**Comment by Sqvid** [comment]
@Ryo-not-rio 
> Could we get some perf numbers

On Neoverse-V1:
main: 15006e116731b219d7a11584461dd146be3a546c

**Before:**
*Note that this fails correctness*
```
$ ./build-main/tests/benchdnn/benchdnn --matmul --mode=P --perf-template='perf,%impl%,%prb%,%+ctime%,%-time%,%0time%,%+time%' --global-skip-impl='ref,simple' --stag=acbd --wtag=acbd --dtag=acbd --attr-fpmath=,bf16 16x64x512x512:16x1x512x256
Output template: perf,%impl%,%prb%,%+ctime%,%-time%,%0time%,%+time%
perf,brg:sve_256,--mode=P --matmul --stag=acbd --wtag=acbd --dtag=acbd --skip-impl=ref,simple 16x64x512x512:16x1x512x256,0.615479,54.187,54.4207,55.7039
perf,brg:sve_256,--mode=P --matmul --stag=acbd --wtag=acbd --dtag=acbd --attr-fpmath=bf16 --skip-impl=ref,simple 16x64x512x512:16x1x512x256,0.236084,54.209,54.3627,55.3125
tests:2 passed:2 skipped:0 mistrusted:0 unimplemented:0 invalid_arguments:0 failed:0 listed:0
total perf: min(ms):108.396 avg(ms):108.783
total: 7.86s; create_pd: 0.00s (0%); create_prim: 0.00s (0%); fill: 0.31s (4%); execute: 0.11s (1%);
```

**After:**
*Passes correctness*
```
$ ./build-pr/tests/benchdnn/benchdnn --matmul --mode=P --perf-template='perf,%impl%,%prb%,%+ctime%,%-time%,%0time%,%+time%' --global-skip-impl='ref,simple' --stag=acbd --wtag=acbd --dtag=acbd --attr-fpmath=,bf16 16x64x512x512:16x1x512x256
Output template: perf,%impl%,%prb%,%+ctime%,%-time%,%0time%,%+time%
perf,brg:sve_256,--mode=P --matmul --stag=acbd --wtag=acbd --dtag=acbd --skip-impl=ref,simple 16x64x512x512:16x1x512x256,0.634766,54.314,54.5365,54.8601
perf,brg:sve_256,--mode=P --matmul --stag=acbd --wtag=acbd --dtag=acbd --attr-fpmath=bf16 --skip-impl=ref,simple 16x64x512x512:16x1x512x256,0.279053,54.2559,54.3574,54.4897
tests:2 passed:2 skipped:0 mistrusted:0 unimplemented:0 invalid_arguments:0 failed:0 listed:0
total perf: min(ms):108.57 avg(ms):108.894
total: 7.84s; create_pd: 0.00s (0%); create_prim: 0.00s (0%); fill: 0.30s (4%); execute: 0.11s (1%);
```

You can also refer to this Nightly which I modified to run correctness on `"matmul|brgemm|conv"` as well as the standard performance tests.

https://github.com/uxlfoundation/oneDNN/actions/runs/18377028966

File: src/cpu/aarch64/matmul/brgemm_matmul_utils.cpp [hunk 4]
```diff
@@ -1048,13 +1062,22 @@ void init_aux_values(brgemm_matmul_conf_t &bgmmc,
...
-                * factor;
+    // If weights have dimensions equal to 1, multiple tags can be matched so
+    // we need to make sure:
+    // - B_ptr_shift_b is set for acbd and adbc even if bgmmc.wei_tag is abcd
+    // - Plain md that matches acbd or adbc does not dispatch into their codepath
+    // - Plain md that matches transposed tag does not dispatch into its codepath
+    if (wei_d.matches_one_of_tag(acbd, adbc) != format_tag::undef) {
+        if (wei_d.matches_one_of_tag(abcd, abdc) == format_tag::undef) {
+            const dim_t factor = bgmmc.wei_dt == f32 ? 2 : 1;
+            const dim_t wei_stride = bgmmc.wei_tag == acbd ? bgmmc.B_strides[1]
```
Comment (Ryo-not-rio) [inline src/cpu/aarch64/matmul/brgemm_matmul_utils.cpp]:
```suggestion
            const dim_t wei_stride = wei_d.matches_tag(acbd) ? bgmmc.B_strides[1]
```
or is wei_d and bgmmc.wei_tag different?

File: src/cpu/aarch64/matmul/brgemm_matmul_utils.cpp (hunk 1 above)
Comment (jondea) [reply src/cpu/aarch64/matmul/brgemm_matmul_utils.cpp:229]: Excellet, thank you!

File: src/cpu/aarch64/matmul/brgemm_matmul_utils.cpp (hunk 4 above)
Comment (Sqvid) [reply src/cpu/aarch64/matmul/brgemm_matmul_utils.cpp]: They are subtly different, but in this particular case they will always agree. I think it is more direct to just use the `struct` member than make a function call.

**Comment by jondea** [comment]
> > Can we not disambiguate the tag once at the start for each tensor, and continue as before?
> 
> I think a lot of `tag`-based logic exists throughout the kernel and I'd rather not mix that simplification in with this change. Going forward it would be better if based our logic on strides and dimensions rather than memory tags.

That's fair enough, and the first priority is the fix. What I mean to say more generally is that it is reasonable to think in terms of a canonical tag, or perhaps more specifically in terms of strategy. E.g. do we transpose or not. The problem is not that we have tags, but the repeated use of `matches_tag` and the ambiguity of that function.

**Comment by Sqvid** [comment]
@jondea 
> The problem is not that we have tags, but the repeated use of matches_tag and the ambiguity of that function.

Yes agreed!

**Comment by Sqvid** [comment]
Don't merge this just yet. I'd like to double-check some of my logic.

**Comment by Sqvid** [comment]
Will merge when CI passes.

File: src/cpu/aarch64/matmul/brgemm_matmul_utils.cpp (hunk 4 above)
Comment (Sqvid) [reply src/cpu/aarch64/matmul/brgemm_matmul_utils.cpp]: I changed all those instances to `matches_tag` to avoid the headache of checking when it is safe.
