### PR TITLE
Drop uneeded immintrin.h

### LINKED ISSUE #1137: Build issue:  immintrin.h: included on non-x86 arches
# Summary
There is a compilation issue on non-x86 arches where immintrin.h is included despite non been available on aarch64 and ppc64le compiler.
The following message can be seen:
  `oneDNN-2.3.2/src/gpu/jit/ngen/ngen_utils.hpp:22:10: fatal error: immintrin.h: No such file or directory`

# Version
2.3.2

# Environment
* CPU: aarch64 & ppc64le
* OS version: Fedora 35
* Compiler version: gcc-11
* CMake version : 2.21
* CMake output log

# Steps to reproduce
Build with   -DDNNL_GPU_RUNTIME=OCL -DDNNL_ARCH_OPT_FLAGS="" 

# Observed behavior
  `oneDNN-2.3.2/src/gpu/jit/ngen/ngen_utils.hpp:22:10: fatal error: immintrin.h: No such file or directory`

# Expected behavior
Build should pass on theses arches.

I'm currently testing few cases:
- if the issue can be workaround by any cmake build option
- also if using #ifdef __INTEL_COMPILER guard before the header (as done in others cases) will help...
Will report.

Side note: I'm the fedora package maintainer of onednn.

### PR DESCRIPTION
**Pull request by kwizart**
# Description
This fixes compilation on non-x86 arches
Fixes #1137

Signed-off-by: Nicolas Chauvet <kwizart@gmail.com>

# Checklist

## General

- [X] Do all unit and benchdnn tests (`make test` and `make test_benchdnn_*`) pass locally for each commit?
- [X] Have you formatted the code using clang-format?

### CODE REVIEW

File: src/gpu/jit/ngen/ngen_utils.hpp [hunk 1]
```diff
@@ -19,7 +19,9 @@
 
 #include <cstdint>
 
+#ifdef __INTEL_COMPILER
```
Comment (densamoilov) [inline src/gpu/jit/ngen/ngen_utils.hpp:22]: Since `immintrin.h` is not Intel Compiler specific but rather X86-64 specific the condition seems to be incorrect. We do use the condition in other places but it's probably because we want to use intrinsics only with Intel Compiler.
The right condition would be `#if defined(__x86_64__) || defined(_M_X64)`.

Also, some functionality from the header must be used somewhere so excluding the header without guarding those places should cause issues at build time. Does the code compile when the header is excluded?

Comment (kwizart) [reply src/gpu/jit/ngen/ngen_utils.hpp:22]: Yes, the code compile with the code been excluded that way.
So indeed, It might be possible to remove the include... (tested with gcc on fedora)

Comment (rjoursler) [reply src/gpu/jit/ngen/ngen_utils.hpp:22]: I could not find any intrinsics from that header used in the ngen code. Likely the intrinsics were later replaced with the `__builtin_*`  functions used in `bsf`, `bsr`, and `popcnt` functions so it is now unneeded.

Comment (densamoilov) [reply src/gpu/jit/ngen/ngen_utils.hpp:22]: Alright, let's remove it then.

Comment (kwizart) [reply src/gpu/jit/ngen/ngen_utils.hpp]: Forced pushed a new commit to drop the immintrin.h header instead.

**Review by rjoursler — APPROVED** [review]

File: src/gpu/jit/ngen/ngen_utils.hpp (hunk 1 above)
Comment (densamoilov) [reply src/gpu/jit/ngen/ngen_utils.hpp]: @kwizart I'll pull this PR in by end of this week.

**Review by densamoilov — APPROVED** [review]

**Comment by densamoilov** [comment]
Thanks for your contribution.
