### PR TITLE
gpu: nvidia: conv: Fix int8 convolution primitive fails

### LINKED ISSUE #1749: [nvidia] int8 convolution primitive fails correctness check
# Summary
oneDNN validation for Nvidia backend hits a correctness issue under benchdnn on int8 convolution problems with dst scale set.

# Steps to reproduce
## Build
```
mkdir -p build
cd build
cmake .. -DCMAKE_BUILD_TYPE=release (or debug) -DDNNL_CPU_RUNTIME=DPCPP (or NONE) -DDNNL_GPU_RUNTIME=DPCPP -DDNNL_GPU_VENDOR=NVIDIA -DONEDNN_BUILD_GRAPH=OFF
cmake --build . --target benchdnn
```

## Run
```
benchdnn --conv --engine=gpu --dir=FWD_I --dt=s8:s8:s8 --attr-scales=dst:common:2 g4ic20ih5oc20oh5kh3ph1n"2d_tail_conv:grouped"
```

# Observed behavior
Failures are reproducible within a single run.
```
run: --mode-modifier=P --conv --engine=gpu --dir=FWD_I --dt=s8:s8:s8 --attr-scales=dst:common:2 g4ic20ih5oc20oh5kh3ph1n"2d_tail_conv:grouped"
[  91][DST][0:3:3:1] exp_f32:         -74 exp:         -74 got:         -64 diff:      10 rdiff:0.135135
[ 289][DST][0:11:2:4] exp_f32:         -68 exp:         -68 got:         -64 diff:       4 rdiff:0.0588235
[ 736][DST][1:9:2:1] exp_f32:          79 exp:          79 got:          64 diff:      15 rdiff:0.189873
[ 813][DST][1:12:2:3] exp_f32:         -71 exp:         -71 got:         -64 diff:       7 rdiff:0.0985916
[ 858][DST][1:14:1:3] exp_f32:         -68 exp:         -68 got:         -64 diff:       4 rdiff:0.0588235
[COMPARE_STATS][DST]: trh=0 max_diff:      15 max_rdiff:0.189873
2207:FAILED (errors:5 total:1000) __REPRO: --mode-modifier=P --conv --engine=gpu --dir=FWD_I --dt=s8:s8:s8 --attr-scales=dst:common:2 g4ic20ih5oc20oh5kh3ph1n"2d_tail_conv:grouped"
```

The reason for failures is incorrect scale handling. Instead of applying it over f32 output coming from accumulation, it down converts the output value into s8 first. Such conversion saturates the output and only then applies the scale which leads to a mismatched result.

### PR DESCRIPTION
**Pull request by kala855**
# Description

When destination scaling is applied to int8 data types some benchmarks fails. This happened because the scaling was applied over the int8 result causing saturation issues.

Fixes #1749

## Solution:

We create a temporal vector to save the values in `f32` and keep the computation as expected by oneDNN. The `scratchpad_size` is modified because of this change. We launch `cudnnConvolutionForward` to obtain its result as `f32`. We apply the scaling parameters for `src/wei` at this stage. After the post-operations, we apply the scaling for `dst` over the `f32` result to avoid saturation issues. Finally, the result is converted to `s8`.

# Checklist

## General

- [x] Do all unit and benchdnn tests (`make test` and `make test_benchdnn_*`) pass locally for each commit?
- [x] Have you formatted the code using clang-format?

### Bug fixes

- [x] Have you included information on how to reproduce the issue (either in a github issue or in this PR)?

### CODE REVIEW

File: src/gpu/nvidia/cudnn_convolution_impl.hpp [hunk 1]
```diff
@@ -521,6 +521,13 @@ struct cudnn_convolution_impl_fwd_t : public cudnn_convolution_impl_base_t {
                         (CUdeviceptr)wei_scale, sizeof(float));
                 scale *= host_wei_scale;
             }
+            if (dst_scale) {
```
[the remark this answers is not in the document]
Comment (kala855) [reply src/gpu/nvidia/cudnn_convolution_impl.hpp:524]: Checking oneDNN [documentation](https://oneapi-src.github.io/oneDNN/dev_guide_attributes_quantization.html) about quantization we get the following formula:

image

Should we follow the same structure pointed there? Do the convolution to get a s32 output, convert it to f32 and apply the scaling factor after post-ops.

[the remark this answers is not in the document]
Comment (vpirogov) [reply src/gpu/nvidia/cudnn_convolution_impl.hpp:524]: Igor is out for the next few weeks.

+@mgouicem, @dzarukin

[the remark this answers is not in the document]
Comment (mgouicem) [reply src/gpu/nvidia/cudnn_convolution_impl.hpp:524]: @kala855 , yes the dst quantization parameters have to be applied after post-ops.
Only the compensation related to src/wei quantization parameters have to be applied right after the f32 conversion (as specified by the formula)

**Comment by vpirogov** [comment]
Just a reminder that [oneDNN v3.4 code freeze](https://github.com/oneapi-src/oneDNN/milestone/20) is coming on January 26.

**Comment by kala855** [comment]
We have updated the PR. We follow the equation to apply the destination scaling after the post-operations. As `cudnnConvolutionForward` does not support having its output in `s32` format, we follow a process to obtain it as an `f32` value when the inputs are `s8`. Then, the scaling parameters for `src/wei` are applied. Finally, after the post-operations, the scaling for `dst` is applied over the `f32` value, which is then converted to `s8`.

File: src/gpu/nvidia/cudnn_convolution_impl.hpp [hunk 2]
```diff
@@ -604,9 +670,18 @@ struct cudnn_convolution_impl_fwd_t : public cudnn_convolution_impl_base_t {
                 = utils::downcast<sycl_cuda_stream_t *>(service_stream);
         auto handle = cuda_stream->get_cudnn_handle();
 
-        CHECK(CUDNN_EXECUTE_FUNC_S(cudnnGetConvolutionForwardWorkspaceSize,
-                handle, descs[x], weights_desc, conv_desc, descs[y],
-                fwd_alg_kind, &scratchpad_size));
+        if (data_types[y] == CUDNN_DATA_INT8 && do_scaling) {
```
Comment (kala855) [inline src/gpu/nvidia/cudnn_convolution_impl.hpp:673]: `do_scaling` is a variable that is `true` if any of the `attr-scales` is used. Is there any way to know on this function if the scaling is applied just to the destination ?

File: src/gpu/nvidia/cudnn_convolution_impl.hpp [hunk 3]
```diff
@@ -523,32 +524,72 @@ struct cudnn_convolution_impl_fwd_t : public cudnn_convolution_impl_base_t {
...
-            } else {
-                CUDNN_CHECK_V(err);
+        float *y_fp32_data = nullptr;
+        dim_t size_output = 1;
+        if (dst_scale && data_types[io::y] == CUDNN_DATA_INT8) {
+            // Compute the size output to pass as a parameter to the
+            // memory allocation call.
+            for (size_t i = 0; i < ndims[io::y]; i++)
+                size_output *= dims[io::y][i];
+            CUDA_EXECUTE_FUNC(cuMemAlloc, (CUdeviceptr *)&y_fp32_data,
```
[the remark this answers is not in the document]
Comment (kala855) [reply src/gpu/nvidia/cudnn_convolution_impl.hpp]: We did use `scratchpad` instead of runtime memory allocation. We needed to change some additional files to get things to work. Let me know if there are new suggestions. Thanks.

File: src/gpu/nvidia/cudnn_convolution_impl.hpp [hunk 4]
```diff
@@ -581,8 +622,32 @@ struct cudnn_convolution_impl_fwd_t : public cudnn_convolution_impl_base_t {
             CUDA_EXECUTE_FUNC(cuMemcpy, (CUdeviceptr)&host_dst_scale,
                     (CUdeviceptr)dst_scale, sizeof(float));
             float inv_scale = 1.0f / host_dst_scale;
-            CUDNN_EXECUTE_FUNC(
-                    cudnnScaleTensor, handle, descs[io::y], y, &inv_scale);
+            if (data_types[io::y] == CUDNN_DATA_INT8) {
```
Comment (igorsafo) [inline src/gpu/nvidia/cudnn_convolution_impl.hpp:625]: there is a code section above that handles post operations. For example:
```
                case dnnl_eltwise:
                    if (last_op) {
                        execute_eltwise(handle, output, y);
                    } else {
                        execute_eltwise(handle, output, post_op_scratch);
                    }
                    break;
```
eltwise already writes to `output`, so the dst scaling of `y_fp32_data` after should not work correctly as the eltwise operation itself, because convolution wrote to `y_fp32_data`. What tests do you run and what GPU are you using?

File: src/gpu/nvidia/cudnn_convolution_impl.hpp [hunk 5]
```diff
@@ -581,8 +622,32 @@ struct cudnn_convolution_impl_fwd_t : public cudnn_convolution_impl_base_t {
...
+                cudnnOpTensorDescriptor_t opTensorDesc;
+                CUDNN_EXECUTE_FUNC_V(
+                        cudnnCreateOpTensorDescriptor, &opTensorDesc);
```
Comment (igorsafo) [inline src/gpu/nvidia/cudnn_convolution_impl.hpp:628]: Please don't create objects at execution. oneDNN has a primitive creation where all these objects can be pre-created similar to scratchpad memory, so at execution they are just used without an overhead.

File: src/gpu/nvidia/cudnn_convolution_impl.hpp [hunk 6]
```diff
@@ -581,8 +622,32 @@ struct cudnn_convolution_impl_fwd_t : public cudnn_convolution_impl_base_t {
...
+                        opTensorOp, opTensorCompType, opTensorNanOpt);
+
+                float alpha_beta = 0.0f;
+                CUDNN_EXECUTE_FUNC(cudnnOpTensor, handle, opTensorDesc,
+                        &inv_scale, y_fp32_desc, y_fp32_data, &alpha_beta,
+                        y_fp32_desc, y_fp32_data, &alpha_beta, descs[io::y], y);
+
+                if (y_fp32_desc)
+                    CUDNN_EXECUTE_FUNC_V(
+                            cudnnDestroyTensorDescriptor, y_fp32_desc);
```
Comment (igorsafo) [inline src/gpu/nvidia/cudnn_convolution_impl.hpp:643]: This object is created once at primitive creation stage (in `init_scratchpad`). Deallocation should happen in primitive implementation destructor to keep the object alive through primitive object lifetime. With the deallocation in the current  location if user calls execution more than once it will fail, because at the first execution the object was destroyed.

File: src/gpu/nvidia/cudnn_convolution_impl.hpp [hunk 7]
```diff
@@ -594,9 +659,21 @@ struct cudnn_convolution_impl_fwd_t : public cudnn_convolution_impl_base_t {
                 = utils::downcast<sycl_cuda_stream_t *>(service_stream);
         auto handle = cuda_stream->get_cudnn_handle();
 
-        CHECK(CUDNN_EXECUTE_FUNC_S(cudnnGetConvolutionForwardWorkspaceSize,
-                handle, descs[x], weights_desc, conv_desc, descs[y],
-                fwd_alg_kind, &scratchpad_size));
+        // The scratchpad size will need to be modified in
+        // cases where the dst_scaling is used and the output
+        // uses s8 values.
+        if (use_scales_dst_) {
```
Comment (igorsafo) [inline src/gpu/nvidia/cudnn_convolution_impl.hpp:665]: As I mentioned before there is already a scratchpad memory reserved which is called `post_op_scratch`. How does it work with the new scratchpad? I think the right way is to reuse it, because its main purpose was to handle cases with post ops and s8 dst:
https://github.com/oneapi-src/oneDNN/blob/274ee103c0c45dbb8aa255203d3d8627dda7ed3f/src/gpu/nvidia/cudnn_convolution.hpp#L101-L105
The current approach is:
`CONV(src, wei) -> dst(s32/f32) -> REORDER-> post_op_scratch(f32) -> POSTOPS -> REORDER->dst(dst_dt) -> DST_SCALE(dst_scale_f32) -> dst(dst_dt)`
The issue in the current approach is that dst scaling happens after quantization reorder, but it should move before:
`CONV(src, wei) -> dst(s32/f32) -> REORDER-> post_op_scratch(f32) -> POSTOPS  -> DST_SCALE(dst_scale_f32) -> REORDER->dst(dst_dt)`

File: src/gpu/nvidia/cudnn_convolution_impl.hpp (hunk 2 above)
Comment (igorsafo) [reply src/gpu/nvidia/cudnn_convolution_impl.hpp]: It can be obtained from pd attributes: 
`do_dst_scaling = !pd()->attr()->scales_.get(DNNL_ARG_DST).has_default_values();`
It could be done in `configure_parameters` right after `do_scaling`:
https://github.com/oneapi-src/oneDNN/blob/274ee103c0c45dbb8aa255203d3d8627dda7ed3f/src/gpu/nvidia/cudnn_convolution_impl.hpp#L136

File: src/gpu/nvidia/cudnn_convolution_impl.hpp (hunk 4 above)
Comment (kala855) [reply src/gpu/nvidia/cudnn_convolution_impl.hpp:625]: I just wanted to let you know that I got your point here. I will double-check it.

I used to run these two batch test files:
```c++
./benchdnn --conv --engine=gpu --batch=test_conv_gpu
./benchdnn --conv --engine=gpu --dt=s8:s8:s8 --dir=FWD_I --skip-impl=ref --attr-scales=src:common:2 --batch=set_conv_all
```
If there is any additional file to test please let me know.
I am using an NVIDIA A100-PCIE-40GB GPU.
Thanks for your feedback.

Comment (igorsafo) [reply src/gpu/nvidia/cudnn_convolution_impl.hpp:625]: The tests should include post-ops, src and dst scales to validate the code path you modified:
`./benchdnn --conv --engine=gpu --dt=s8:s8:s8 --dir=FWD_I --skip-impl=ref --attr-scales=src:common:2+dst:common:4 --attr-post-ops=eltwise_relu --batch=set_conv_all`
- The src scales should enforce the implementation to compute into f32 accumulator;
- The post-ops will use `tmp_dst`
- The dst scales is what is broken currently.

I would also recommend to play a bit with dst scales value (4 in this example) to make sure that if conversion f32->s8 is before the dst scaling (as it is currently) the test fails due to rounding issues.

Comment (kala855) [reply src/gpu/nvidia/cudnn_convolution_impl.hpp:658]: We took into account the tests you mentioned in this last commit. The reorder is done directly after the scaling. We are not using the `need_reorder` flag. The path that our algorithm is taking is a different one where the reorder process is done after the dst scaling when the function `cudnnOpTensor` is used.

File: src/gpu/nvidia/cudnn_convolution_impl.hpp (hunk 5 above)
Comment (kala855) [reply src/gpu/nvidia/cudnn_convolution_impl.hpp]: This was fixed in the current commit. Thanks for the feedback.

File: src/gpu/nvidia/cudnn_convolution_impl.hpp (hunk 7 above)
Comment (kala855) [reply src/gpu/nvidia/cudnn_convolution_impl.hpp:681]: The current approach is doing the reorder after the dst scaling. That part is done during the `cudnnOpTensor``function call. That function scales de dst first and then applies a `reorder`.

Thanks for the feedback provided.

File: src/gpu/nvidia/cudnn_convolution_impl.hpp (hunk 4 above)
Comment (igorsafo) [reply src/gpu/nvidia/cudnn_convolution_impl.hpp:658]: Thanks for updating the code, the following test case still fails:
`--conv --engine=gpu --skip-impl=ref --dir=FWD_I --dt=s8:s8:s8 --attr-scales=src:common:2+dst:common:4 --attr-post-ops=sum g6ic24iw11oc24ow9kw3pw0n"1d_gconv_channel-block-4"`
I used the following command to make sure post ops are tested (just a relu postop can be fused into cudnn call, so post ops logic will be skipped, but we want to test it):
` ./build/tests/benchdnn/benchdnn --conv --engine=gpu --dt=s8:s8:s8,s8:s8:f32 --dir=FWD_I --skip-impl=ref --attr-scales=src:common:2+dst:common:4 --attr-post-ops=eltwise_relu,sum --batch=set_conv_all`

File: src/gpu/nvidia/cudnn_convolution_impl.hpp [hunk 8]
```diff
@@ -65,7 +65,10 @@ struct cudnn_convolution_impl_base_t
     bool with_bias = false;
 
     bool do_scaling = false;
+    bool do_dst_scaling = false;
+    bool do_dst_scaling = false;
```
Comment (igorsafo) [inline src/gpu/nvidia/cudnn_convolution_impl.hpp:69]: This line breaks the build due to `do_dst_scaling` re-declaration, please fix

Comment (kala855) [reply src/gpu/nvidia/cudnn_convolution_impl.hpp]: It is fixed now. Thank you.

File: src/gpu/nvidia/cudnn_convolution_impl.hpp (hunk 4 above)
Comment (kala855) [reply src/gpu/nvidia/cudnn_convolution_impl.hpp:673]: Thanks for the feedback. I did check the code and applied some changes to avoid the reported issue. I tested locally and the benchdnn tests are passing.

Comment (igorsafo) [reply src/gpu/nvidia/cudnn_convolution_impl.hpp:673]: Thanks for the update!

There is another class of test cases that fail: no dst scale, but dst is s8:
```./build/tests/benchdnn/benchdnn --conv --engine=gpu --skip-impl=ref --dir=FWD_I --dt=s8:s8:s8 --attr-scales=src:common:2 --attr-post-ops=sum mb1ic512iw121oc512ow122kw6pw3nconv1d:21```

Even dst scale is not set, the post ops computation should happen in f32 and then quantized  but the dst_scale will be equal to `1` (default scale value).

**Review by igorsafo — CHANGES_REQUESTED** [review]
There is another class of test cases that fail: no dst scale, but dst is s8:
./build/tests/benchdnn/benchdnn --conv --engine=gpu --skip-impl=ref --dir=FWD_I --dt=s8:s8:s8 --attr-scales=src:common:2 --attr-post-ops=sum mb1ic512iw121oc512ow122kw6pw3nconv1d:21

Even dst scale is not set, the post ops computation should happen in f32 and then the dst should be quantized but the dst_scale will be equal to 1 (default scale value).

File: src/gpu/nvidia/cudnn_convolution_impl.hpp (hunk 4 above)
Comment (kala855) [reply src/gpu/nvidia/cudnn_convolution_impl.hpp:688]: Thanks for letting me know this is an issue @igorsafo. I did some fixes to support these cases. In the last commit, I addressed them. If there's something else to check please let me know.

File: src/gpu/nvidia/cudnn_convolution_impl.hpp [hunk 9]
```diff
@@ -495,6 +549,11 @@ struct cudnn_convolution_impl_fwd_t : public cudnn_convolution_impl_base_t {
             weights = w_scratch;
         }
 
+        float *y_fp32_data = nullptr;
+        if ((dst_scale || src_scale) && data_types[io::y] == CUDNN_DATA_INT8) {
```
Comment (igorsafo) [inline src/gpu/nvidia/cudnn_convolution_impl.hpp:553]: To simplify reading, avoid bugs and to remove copy-paste I would recommend to create a method for the following and reuse it everywhere:
`bool y_f32_is_required() const { return (do_src_scaling || do_dst_scaling || do _wei_scaling) && data_types[io::y] == CUDNN_DATA_INT8; }`

File: src/gpu/nvidia/cudnn_convolution_impl.hpp [hunk 10]
```diff
@@ -440,19 +460,37 @@ struct cudnn_convolution_impl_fwd_t : public cudnn_convolution_impl_base_t {
...
+        if (data_types[y] == CUDNN_DATA_INT8 && use_temp_dst_
+                && !(do_dst_scaling || do_src_scaling)) {
             data_types[y] = CUDNN_DATA_FLOAT;
             need_reorder = true;
             CHECK(create_and_set_tensor_descriptor_ex(&reorder_dst_desc,
                     formats[y], reorder_type, ndims[y], dims[y]));
         }
 
+        // If dst needs to be scaled and dst datatype is s8
+        if ((do_dst_scaling || do_src_scaling)
```
Comment (igorsafo) [inline src/gpu/nvidia/cudnn_convolution_impl.hpp:476]: Thanks for the fixes, it is getting better.

There is also a weights scale. With the current implementation the following case fails:
```
$ ./build/tests/benchdnn/benchdnn --conv --engine=gpu --skip-impl=ref --dir=FWD_I --dt=s8:s8:s8 --attr-scales=wei:common:2 --attr-post-ops=sum mb1ic512iw121oc512ow122kw6pw3nconv1d:21
[   4][DST][0:0:4] exp_f32:        -156 exp:        -128 got:        -124 diff:       4 rdiff: 0.03125
[   8][DST][0:0:8] exp_f32:         141 exp:         127 got:         124 diff:       3 rdiff:0.023622
[  21][DST][0:0:21] exp_f32:         257 exp:         127 got:         124 diff:       3 rdiff:0.023622
[  36][DST][0:0:36] exp_f32:        -183 exp:        -128 got:        -127 diff:       1 rdiff:0.0078125
[  46][DST][0:0:46] exp_f32:         258 exp:         127 got:         125 diff:       2 rdiff:0.015748
[  60][DST][0:0:60] exp_f32:         137 exp:         127 got:         124 diff:       3 rdiff:0.023622
[  69][DST][0:0:69] exp_f32:        -161 exp:        -128 got:        -125 diff:       3 rdiff:0.0234375
[  74][DST][0:0:74] exp_f32:         140 exp:         127 got:         123 diff:       4 rdiff:0.0314961
[  88][DST][0:0:88] exp_f32:         129 exp:         127 got:         124 diff:       3 rdiff:0.023622
[  92][DST][0:0:92] exp_f32:         250 exp:         127 got:         125 diff:       2 rdiff:0.015748
[COMPARE_STATS][DST]: trh=0 max_diff:       4 max_rdiff:0.0314961
0:FAILED (errors:5371 total:62464) __REPRO: --conv --engine=gpu --skip-impl=ref --dir=FWD_I --dt=s8:s8:s8 --attr-scales=wei:common:2 --attr-post-ops=sum mb1ic512iw121oc512ow122kw6pw3nconv1d:21
tests:1 passed:0 skipped:0 mistrusted:0 unimplemented:0 invalid_arguments:0 failed:1 listed:0
total: 1.68s; fill: 0.02s (1%); compute_ref: 0.02s (1%); compare: 0.01s (0%);

```

File: src/gpu/nvidia/cudnn_convolution_impl.hpp (hunk 9 above)
Comment (kala855) [reply src/gpu/nvidia/cudnn_convolution_impl.hpp]: I added the new function and is being called where needed. If you find some additional place to use it please let me know. Thanks.

File: src/gpu/nvidia/cudnn_convolution_impl.hpp (hunk 10 above)
Comment (kala855) [reply src/gpu/nvidia/cudnn_convolution_impl.hpp]: Thanks for the feedback again @igorsafo.
I added the code to take care of weight scales. I run the example and now it is working.
Please let me know about any new potential changes to apply.

Comment (igorsafo) [reply src/gpu/nvidia/cudnn_convolution_impl.hpp]: @kala855  thanks, now it works on my side. There is another issue related to the sum post op. It fails with or without scales, but only with s8 dst type:
```
$ ./build/tests/benchdnn/benchdnn --conv --engine=gpu --skip-impl=ref --dir=FWD_D --dt=s8:s8:s8  --attr-post-ops=sum:2 g1ic32ih149oc32oh147kh3ph0n"googlenet_v3:conv_1_1_conv2d"
[ 140][DST][0:0:0:140] exp_f32:         126 exp:         126 got:         121 diff:       5 rdiff:0.0396825
[ 186][DST][0:0:1:39] exp_f32:        -132 exp:        -128 got:        -120 diff:       8 rdiff:  0.0625
[ 363][DST][0:0:2:69] exp_f32:        -130 exp:        -128 got:        -126 diff:       2 rdiff:0.015625
[ 574][DST][0:0:3:133] exp_f32:        -154 exp:        -128 got:        -124 diff:       4 rdiff: 0.03125
[ 607][DST][0:0:4:19] exp_f32:        -146 exp:        -128 got:        -124 diff:       4 rdiff: 0.03125
[ 894][DST][0:0:6:12] exp_f32:        -126 exp:        -126 got:        -122 diff:       4 rdiff:0.031746
[1188][DST][0:0:8:12] exp_f32:         148 exp:         127 got:         121 diff:       6 rdiff:0.0472441
[1551][DST][0:0:10:81] exp_f32:         142 exp:         127 got:         123 diff:       4 rdiff:0.0314961
[1680][DST][0:0:11:63] exp_f32:        -154 exp:        -128 got:        -120 diff:       8 rdiff:  0.0625
[1716][DST][0:0:11:99] exp_f32:        -134 exp:        -128 got:        -126 diff:       2 rdiff:0.015625
[COMPARE_STATS][DST]: trh=0 max_diff:       8 max_rdiff:0.0629921
0:FAILED (errors:7570 total:1382976) __REPRO: --conv --engine=gpu --skip-impl=ref --dir=FWD_D --dt=s8:s8:s8 --attr-post-ops=sum:2 g1ic32ih149oc32oh147kh3ph0ngooglenet_v3:conv_1_1_conv2d
tests:1 passed:0 skipped:0 mistrusted:0 unimplemented:0 invalid_arguments:0 failed:1 listed:0
total: 1.69s; fill: 0.04s (2%); compute_ref: 0.03s (2%); compare: 0.05s (3%);
$ ./build/tests/benchdnn/benchdnn --conv --engine=gpu --skip-impl=ref --dir=FWD_D --dt=s8:s8:f32  --attr-post-ops=sum:2 g1ic32ih149oc32oh147kh3ph0n"googlenet_v3:conv_1_1_conv2d"
0:PASSED __REPRO: --conv --engine=gpu --skip-impl=ref --dir=FWD_D --dt=s8:s8:f32 --attr-post-ops=sum:2 g1ic32ih149oc32oh147kh3ph0ngooglenet_v3:conv_1_1_conv2d
tests:1 passed:1 skipped:0 mistrusted:0 unimplemented:0 invalid_arguments:0 failed:0 listed:0
total: 1.64s; fill: 0.03s (2%); compute_ref: 0.05s (3%); compare: 0.01s (1%);
```

I found the issue by running `./build/tests/benchdnn/benchdnn --conv --engine=gpu --batch=tests/benchdnn/inputs/conv/test_conv_int8`

Comment (kala855) [reply src/gpu/nvidia/cudnn_convolution_impl.hpp]: @igorsafo Thanks, I was checking this issue but it seems like it is not related to the scaling parameter issues with int8 as reported in issue #1749. I could open and start solving a new issue to deal with this sum post-op problem. Let me know if it is OK. Thank you.

File: src/gpu/nvidia/cudnn_convolution_impl.hpp [hunk 11]
```diff
@@ -563,7 +667,13 @@ struct cudnn_convolution_impl_fwd_t : public cudnn_convolution_impl_base_t {
 
                 case dnnl_eltwise:
                     if (last_op) {
-                        execute_eltwise(handle, output, y);
+                        if ((dst_scale || src_scale || wei_scale)
+                                && data_types[io::y] == CUDNN_DATA_INT8) {
```
Comment (igorsafo) [inline src/gpu/nvidia/cudnn_convolution_impl.hpp:671]:
```suggestion
                        if (y_f32_is_required()) {
```

**Review by igorsafo — APPROVED** [review]

File: src/gpu/nvidia/cudnn_convolution_impl.hpp (hunk 10 above)
Comment (igorsafo) [reply src/gpu/nvidia/cudnn_convolution_impl.hpp]: @kala855 , Agree, I was able to reproduce the issue prior to the changes in this PR.
Here is a separate issue: https://github.com/oneapi-src/oneDNN/issues/1870

**Comment by dzarukin** [comment]
Please squash all the changes and remove all `merge` commits - the history must be linear.

**Comment by kala855** [comment]
@dzarukin I did the squash as you mentioned. Thank you very much. Let me know if something else needs to be done.

**Comment by dzarukin** [comment]
Thanks for the contribution.
