### PR TITLE
Fix simple reorder

### LINKED ISSUE #1272: rls-v2.5 benchdnn reorder on AArch64 failed
# Summary

Two problems of `./benchdnn --reorder --batch=inputs/reorder/test_reorder_all` failed
(The master branch with my patch https://github.com/kawakami-k/oneDNN/tree/issue1256 for AArch64 also failed with these two problems.)

# Version

rls-v2.5
543b8f86f4659d36dddcff1d2bddb810d3740889

# Environment

## Mac Mini (M1)
* CPU: M1
* OS: macOS Monterey 12.2
* cmake: 3.19.2
* Compiler: Apple clang version 12.0.5 (clang=1205.0.22.9)

## FX700 (A64FX), 
* CPU: A64FX
* OS: CentOS 8
* cmake: 3.11.4
* gcc: 8.3.1 20190507 (Red Hat 8.3.1-4)

# Steps to reproduce

```
./benchdnn --reorder --sdt=f32 --ddt=f32 --stag=aBx16b --dtag=aBx4b --attr-oscale=common:4.29497e+09 1x17x9x5
./benchdnn --reorder --sdt=f32 --ddt=f32 --stag=aBx16b --dtag=aBx8b --attr-oscale=common:4.29497e+09 1x17x9x5
```

# Observed behavior

```
[ 721][arg:17][0,17,0,0,0,0] fp:  0.f dt:     -nan 
[ 725][arg:17][0,17,0,1,0,0] fp:  0.f dt:     -nan 
[ 729][arg:17][0,17,0,2,0,0] fp:  0.f dt:     -nan 
[ 733][arg:17][0,17,0,3,0,0] fp:  0.f dt:     -nan 
[ 737][arg:17][0,17,0,4,0,0] fp:  0.f dt:     -nan 
[ 741][arg:17][0,17,1,0,0,0] fp:  0.f dt:     -nan 
[ 745][arg:17][0,17,1,1,0,0] fp:  0.f dt:     -nan 
[ 749][arg:17][0,17,1,2,0,0] fp:  0.f dt:     -nan 
[ 753][arg:17][0,17,1,3,0,0] fp:  0.f dt:     -nan 
@@@ [arg:17] check_zero_padding failed
21982:UNTESTED_FAILED (errors:0 total:0) __REPRO: --reorder --sdt=f32 --ddt=f32 --stag=aBx16b --dtag=aBx4b --attr-oscale=common:4.29497e+09 1x17x9x5
[ 721][arg:17][0,17,0,0,0,0] fp:  0.f dt:     -nan 
[ 729][arg:17][0,17,0,1,0,0] fp:  0.f dt:     -nan 
[ 737][arg:17][0,17,0,2,0,0] fp:  0.f dt:     -nan 
[ 745][arg:17][0,17,0,3,0,0] fp:  0.f dt:     -nan 
[ 753][arg:17][0,17,0,4,0,0] fp:  0.f dt:     -nan 
[ 761][arg:17][0,17,1,0,0,0] fp:  0.f dt:     -nan 
[ 769][arg:17][0,17,1,1,0,0] fp:  0.f dt:     -nan 
[ 777][arg:17][0,17,1,2,0,0] fp:  0.f dt:     -nan 
[ 785][arg:17][0,17,1,3,0,0] fp:  0.f dt:     -nan 
@@@ [arg:17] check_zero_padding failed
21983:UNTESTED_FAILED (errors:0 total:0) __REPRO: --reorder --sdt=f32 --ddt=f32 --stag=aBx16b --dtag=aBx8b --attr-oscale=common:4.29497e+09 1x17x9x5
```

### PR DESCRIPTION
**Pull request by igorsafo**
# Description

Simple reorder contains a few issues that are not reproducible on x64, because they are disabled. The issues can be reproduced when aarch64 emulation is used:

- Zero padding optimizations bb0f475615097915a17cb0a5cd4a7980d1e84691 introduced an issue by not padding properly in some cases.
- In benchdnn mask is created separately so it doesn't have information about `ndims`. Due to this for `per_tensor` policy the mask is `(1 << DNNL_MAX_NDIMS) - 1` and if implementation relies on the mask this results in an issue. The workaround is to truncate it on the implementation side. An alternative is to forbid to pass such masks and return `invalid_arguments` when `primitive_desc` is being created. Benchdnn should be updated as well to truncate mask on its side.
- Memory descriptor defines size for compensation based on `padded_dims` ( [Link](https://github.com/oneapi-src/oneDNN/blob/682a91bdbcc8e494935f9a4d4b98bcd47ac3bfce/src/common/memory_desc_wrapper.hpp#L121) ), but simple reorder uses logical dims which results in an issue.
- benchdnn contains tests that contains `oscale` mask `per_dim_1`, but it is not supported by `simple_reorder`.

Fixes #1272

# Checklist

## General

- [x] Do all unit and benchdnn tests (`make test` and `make test_benchdnn_*`) pass locally for each commit?
- [x] Have you formatted the code using clang-format?

### CODE REVIEW

File: src/cpu/reorder/simple_reorder.hpp [hunk 1]
```diff
@@ -411,10 +428,9 @@ struct simple_reorder_impl<SIMPLE_REORDER_TEMPL_CALL,
         constexpr dim_t i_mult_oc = ocblksize;
         constexpr dim_t o_mult = 1;
 
-        size_t offset
-                = G * pdims[w_groups + 0] * pdims[w_groups + 1] * D * H * W;
-        size_t zp_offset = offset
-                + (req_comp ? G * dims[w_groups + 0] * sizeof(int32_t) : 0);
+        size_t offset = G * PADDED_OC * pdims[w_groups + 1] * D * H * W;
```
Comment (dzarukin) [inline src/cpu/reorder/simple_reorder.hpp:431]:
```suggestion
        size_t offset = output_d.size() - output_d.additional_buffer_size();
```

**Comment by igorsafo** [comment]
@kawakami-k Could you please validate the fix on your side?

File: src/cpu/reorder/simple_reorder.hpp [hunk 2]
```diff
@@ -198,8 +202,8 @@ struct simple_reorder_impl<SIMPLE_REORDER_TEMPL_CALL,
                 : 1.f;
 
         size_t offset = output_d.size() - output_d.additional_buffer_size();
-        size_t zp_offset = offset
-                + (req_comp ? G * dims[w_groups + 0] * sizeof(int32_t) : 0);
+        size_t zp_offset
+                = offset + (req_comp ? G * PADDED_OC * sizeof(int32_t) : 0);
```
Comment (dzarukin) [inline src/cpu/reorder/simple_reorder.hpp:206]: I would suggest to use a bit more scalable solution (as it seems to me), make `additional_buffer_size()` function to accept an argument (which will be `extra().flags` by default), that chooses the specific comp type. In this case it will be `s8s8_comp`.
Then `zp_offset` can be computed as `output_d.size() - output_d.additional_buffer_size(s8s8_comp)`. No need to follow the padding values, dimensions, etc.
This implicitly relies on the order of compensations, but we still do it any way.

File: src/cpu/reorder/simple_reorder.hpp [hunk 3]
```diff
@@ -355,21 +361,32 @@ struct simple_reorder_impl<SIMPLE_REORDER_TEMPL_CALL,
...
         const dim_t W = is_0d ? 1 : dims[w_groups + is_3d + 3 - is_1d];
 
+        int smask = pd->attr()->output_scales_.mask_;
+        // XXX: Currently user can pass a mask that has non-zero values in
+        // dimensions that do not exist in a md. Since attributes are created
+        // separately mask can't be validated.
+        // This line truncates a given mask in range [0, 1 << ndims - 1]
+        // TODO: Such masks can be either prohibited at pd creation step at
+        // API level or checked by each implementation that relies on it.
+        smask &= (1 << ndims) - 1;
```
Comment (dzarukin) [inline src/cpu/reorder/simple_reorder.hpp:385]: Considering more templated branches may appear, I vote for restricting masks and implement a proper mask passing from benchdnn to be safer in future.

File: src/cpu/reorder/simple_reorder.hpp (hunk 2 above)
Comment (igorsafo) [reply src/cpu/reorder/simple_reorder.hpp]: Makes sense, I added 2 commits to reuse `additional_buffer_size()` for offset calculations.

File: src/cpu/reorder/simple_reorder.hpp (hunk 1 above)
Comment (igorsafo) [reply src/cpu/reorder/simple_reorder.hpp]: Updated the changes , thanks

**Comment by kawakami-k** [comment]
Hi, @igorsafo 

Thank you very much for fixing `simple_reorder`.
Here is the result of `./benchdnn --reorder --batch=test_reorder_all | grep -v PASSED`.

```
26404:FAILED (errors:1 total:70) __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=aBCx4b4c --oflag=s8s8_comp:3 2x35x35x3x3
26405:FAILED (errors:1 total:70) __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=aBCx4b4c --oflag=s8s8_comp:3 --attr-oscale=common:2 2x35x35x3x3
26406:FAILED (errors:1 total:70) __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=aBCx4b4c --oflag=zp_comp:3 2x35x35x3x3
26407:FAILED (errors:1 total:70) __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=aBCx4b4c --oflag=zp_comp:3 --attr-oscale=common:2 2x35x35x3x3
26408:FAILED (errors:1 total:70) __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=aBCx4b4c --oflag=s8s8_comp:3+zp_comp:3 2x35x35x3x3
26409:FAILED (errors:1 total:70) __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=aBCx4b4c --oflag=s8s8_comp:3+zp_comp:3 --attr-oscale=common:2 2x35x35x3x3
26412:FAILED (errors:1 total:70) __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xcab --dtag=aBCx4b4c --oflag=s8s8_comp:3 2x35x35x3x3
26413:FAILED (errors:1 total:70) __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xcab --dtag=aBCx4b4c --oflag=s8s8_comp:3 --attr-oscale=common:2 2x35x35x3x3
26414:FAILED (errors:1 total:70) __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xcab --dtag=aBCx4b4c --oflag=zp_comp:3 2x35x35x3x3
26415:FAILED (errors:1 total:70) __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xcab --dtag=aBCx4b4c --oflag=zp_comp:3 --attr-oscale=common:2 2x35x35x3x3
26416:FAILED (errors:1 total:70) __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xcab --dtag=aBCx4b4c --oflag=s8s8_comp:3+zp_comp:3 2x35x35x3x3
26417:FAILED (errors:1 total:70) __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xcab --dtag=aBCx4b4c --oflag=s8s8_comp:3+zp_comp:3 --attr-oscale=common:2 2x35x35x3x3
26420:FAILED (errors:1 total:70) __REPRO: --reorder --sdt=bf16 --ddt=s8 --stag=abx --dtag=aBCx4b4c --oflag=s8s8_comp:3 2x35x35x3x3
26421:FAILED (errors:1 total:70) __REPRO: --reorder --sdt=bf16 --ddt=s8 --stag=abx --dtag=aBCx4b4c --oflag=s8s8_comp:3 --attr-oscale=common:2 2x35x35x3x3
26422:FAILED (errors:1 total:70) __REPRO: --reorder --sdt=bf16 --ddt=s8 --stag=abx --dtag=aBCx4b4c --oflag=zp_comp:3 2x35x35x3x3
26423:FAILED (errors:1 total:70) __REPRO: --reorder --sdt=bf16 --ddt=s8 --stag=abx --dtag=aBCx4b4c --oflag=zp_comp:3 --attr-oscale=common:2 2x35x35x3x3
26424:FAILED (errors:1 total:70) __REPRO: --reorder --sdt=bf16 --ddt=s8 --stag=abx --dtag=aBCx4b4c --oflag=s8s8_comp:3+zp_comp:3 2x35x35x3x3
26425:FAILED (errors:1 total:70) __REPRO: --reorder --sdt=bf16 --ddt=s8 --stag=abx --dtag=aBCx4b4c --oflag=s8s8_comp:3+zp_comp:3 --attr-oscale=common:2 2x35x35x3x3
26428:FAILED (errors:1 total:70) __REPRO: --reorder --sdt=bf16 --ddt=s8 --stag=xcab --dtag=aBCx4b4c --oflag=s8s8_comp:3 2x35x35x3x3
26429:FAILED (errors:1 total:70) __REPRO: --reorder --sdt=bf16 --ddt=s8 --stag=xcab --dtag=aBCx4b4c --oflag=s8s8_comp:3 --attr-oscale=common:2 2x35x35x3x3
26430:FAILED (errors:1 total:70) __REPRO: --reorder --sdt=bf16 --ddt=s8 --stag=xcab --dtag=aBCx4b4c --oflag=zp_comp:3 2x35x35x3x3
26431:FAILED (errors:1 total:70) __REPRO: --reorder --sdt=bf16 --ddt=s8 --stag=xcab --dtag=aBCx4b4c --oflag=zp_comp:3 --attr-oscale=common:2 2x35x35x3x3
26432:FAILED (errors:1 total:70) __REPRO: --reorder --sdt=bf16 --ddt=s8 --stag=xcab --dtag=aBCx4b4c --oflag=s8s8_comp:3+zp_comp:3 2x35x35x3x3
26433:FAILED (errors:1 total:70) __REPRO: --reorder --sdt=bf16 --ddt=s8 --stag=xcab --dtag=aBCx4b4c --oflag=s8s8_comp:3+zp_comp:3 --attr-oscale=common:2 2x35x35x3x3
26436:FAILED (errors:1 total:70) __REPRO: --reorder --sdt=s8 --ddt=s8 --stag=abx --dtag=aBCx4b4c --oflag=s8s8_comp:3 2x35x35x3x3
26437:FAILED (errors:1 total:70) __REPRO: --reorder --sdt=s8 --ddt=s8 --stag=abx --dtag=aBCx4b4c --oflag=s8s8_comp:3 --attr-oscale=common:2 2x35x35x3x3
26438:FAILED (errors:1 total:70) __REPRO: --reorder --sdt=s8 --ddt=s8 --stag=abx --dtag=aBCx4b4c --oflag=zp_comp:3 2x35x35x3x3
26439:FAILED (errors:1 total:70) __REPRO: --reorder --sdt=s8 --ddt=s8 --stag=abx --dtag=aBCx4b4c --oflag=zp_comp:3 --attr-oscale=common:2 2x35x35x3x3
26440:FAILED (errors:1 total:70) __REPRO: --reorder --sdt=s8 --ddt=s8 --stag=abx --dtag=aBCx4b4c --oflag=s8s8_comp:3+zp_comp:3 2x35x35x3x3
26441:FAILED (errors:1 total:70) __REPRO: --reorder --sdt=s8 --ddt=s8 --stag=abx --dtag=aBCx4b4c --oflag=s8s8_comp:3+zp_comp:3 --attr-oscale=common:2 2x35x35x3x3
26444:FAILED (errors:1 total:70) __REPRO: --reorder --sdt=s8 --ddt=s8 --stag=xcab --dtag=aBCx4b4c --oflag=s8s8_comp:3 2x35x35x3x3
26445:FAILED (errors:1 total:70) __REPRO: --reorder --sdt=s8 --ddt=s8 --stag=xcab --dtag=aBCx4b4c --oflag=s8s8_comp:3 --attr-oscale=common:2 2x35x35x3x3
26446:FAILED (errors:1 total:70) __REPRO: --reorder --sdt=s8 --ddt=s8 --stag=xcab --dtag=aBCx4b4c --oflag=zp_comp:3 2x35x35x3x3
26447:FAILED (errors:1 total:70) __REPRO: --reorder --sdt=s8 --ddt=s8 --stag=xcab --dtag=aBCx4b4c --oflag=zp_comp:3 --attr-oscale=common:2 2x35x35x3x3
26448:FAILED (errors:1 total:70) __REPRO: --reorder --sdt=s8 --ddt=s8 --stag=xcab --dtag=aBCx4b4c --oflag=s8s8_comp:3+zp_comp:3 2x35x35x3x3
26449:FAILED (errors:1 total:70) __REPRO: --reorder --sdt=s8 --ddt=s8 --stag=xcab --dtag=aBCx4b4c --oflag=s8s8_comp:3+zp_comp:3 --attr-oscale=common:2 2x35x35x3x3
fx700-01-05.local:SVE512 /home/kawakami/tmp/oneDNN_simple_reorder/build/tests/benchdnn% grep FAILED test_reorder_all.log | wc -l
36
fx700-01-05.local:SVE512 /home/kawakami/tmp/oneDNN_simple_reorder/build/tests/benchdnn% grep -v PASSED test_reorder_all.log 
8607:SKIPPED (SKIP_IMPL_HIT) __REPRO: --reorder --skip-impl=ref,simple --sdt=f32 --ddt=f32 --stag=abx --dtag=aBx8b 2x16x19200x19200
8608:SKIPPED (NOT_ENOUGH_RAM) __REPRO: --reorder --sdt=f32 --ddt=f32 --stag=abx --dtag=aBx8b 1x4294967296x1
22799:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=xba --oflag=s8s8_comp:1 --attr-oscale=per_dim_1:3 32x32x3
22800:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=xba --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:3 32x32x3
22801:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=xba --oflag=s8s8_comp:1 --attr-oscale=per_tensor:0.7 32x32x3
22805:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=xba --oflag=zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3
22806:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=xba --oflag=zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3
22807:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=xba --oflag=zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3
22811:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=xba --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3
22812:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=xba --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3
22813:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=xba --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3
22823:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx2b8a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_1:3 32x32x3
22824:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx2b8a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:3 32x32x3
22825:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx2b8a4b --oflag=s8s8_comp:1 --attr-oscale=per_tensor:0.7 32x32x3
22829:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx2b8a4b --oflag=zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3
22830:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx2b8a4b --oflag=zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3
22831:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx2b8a4b --oflag=zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3
22835:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx2b8a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3
22836:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx2b8a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3
22837:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx2b8a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3
22847:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_1:3 32x32x3
22848:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:3 32x32x3
22849:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4a4b --oflag=s8s8_comp:1 --attr-oscale=per_tensor:0.7 32x32x3
22853:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4a4b --oflag=zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3
22854:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4a4b --oflag=zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3
22855:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4a4b --oflag=zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3
22859:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3
22860:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3
22861:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3
22871:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b16a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_1:3 32x32x3
22872:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b16a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:3 32x32x3
22873:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b16a4b --oflag=s8s8_comp:1 --attr-oscale=per_tensor:0.7 32x32x3
22877:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b16a4b --oflag=zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3
22878:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b16a4b --oflag=zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3
22879:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b16a4b --oflag=zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3
22883:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b16a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3
22884:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b16a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3
22885:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b16a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3
22895:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b32a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_1:3 32x32x3
22896:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b32a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:3 32x32x3
22897:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b32a4b --oflag=s8s8_comp:1 --attr-oscale=per_tensor:0.7 32x32x3
22901:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b32a4b --oflag=zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3
22902:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b32a4b --oflag=zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3
22903:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b32a4b --oflag=zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3
22907:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b32a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3
22908:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b32a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3
22909:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b32a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3
22919:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b64a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_1:3 32x32x3
22920:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b64a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:3 32x32x3
22921:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b64a4b --oflag=s8s8_comp:1 --attr-oscale=per_tensor:0.7 32x32x3
22925:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b64a4b --oflag=zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3
22926:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b64a4b --oflag=zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3
22927:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b64a4b --oflag=zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3
22931:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b64a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3
22932:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b64a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3
22933:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b64a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3
22943:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=xba --oflag=s8s8_comp:1 --attr-oscale=per_dim_1:3 32x32x3
22944:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=xba --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:3 32x32x3
22945:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=xba --oflag=s8s8_comp:1 --attr-oscale=per_tensor:0.7 32x32x3
22949:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=xba --oflag=zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3
22950:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=xba --oflag=zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3
22951:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=xba --oflag=zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3
22955:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=xba --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3
22956:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=xba --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3
22957:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=xba --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3
22967:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx2b8a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_1:3 32x32x3
22968:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx2b8a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:3 32x32x3
22969:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx2b8a4b --oflag=s8s8_comp:1 --attr-oscale=per_tensor:0.7 32x32x3
22973:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx2b8a4b --oflag=zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3
22974:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx2b8a4b --oflag=zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3
22975:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx2b8a4b --oflag=zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3
22979:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx2b8a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3
22980:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx2b8a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3
22981:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx2b8a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3
22991:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_1:3 32x32x3
22992:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:3 32x32x3
22993:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4a4b --oflag=s8s8_comp:1 --attr-oscale=per_tensor:0.7 32x32x3
22997:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4a4b --oflag=zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3
22998:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4a4b --oflag=zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3
22999:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4a4b --oflag=zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3
23003:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3
23004:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3
23005:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3
23015:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b16a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_1:3 32x32x3
23016:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b16a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:3 32x32x3
23017:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b16a4b --oflag=s8s8_comp:1 --attr-oscale=per_tensor:0.7 32x32x3
23021:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b16a4b --oflag=zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3
23022:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b16a4b --oflag=zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3
23023:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b16a4b --oflag=zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3
23027:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b16a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3
23028:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b16a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3
23029:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b16a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3
23039:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b32a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_1:3 32x32x3
23040:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b32a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:3 32x32x3
23041:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b32a4b --oflag=s8s8_comp:1 --attr-oscale=per_tensor:0.7 32x32x3
23045:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b32a4b --oflag=zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3
23046:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b32a4b --oflag=zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3
23047:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b32a4b --oflag=zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3
23051:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b32a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3
23052:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b32a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3
23053:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b32a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3
23063:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b64a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_1:3 32x32x3
23064:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b64a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:3 32x32x3
23065:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b64a4b --oflag=s8s8_comp:1 --attr-oscale=per_tensor:0.7 32x32x3
23069:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b64a4b --oflag=zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3
23070:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b64a4b --oflag=zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3
23071:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b64a4b --oflag=zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3
23075:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b64a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3
23076:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b64a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3
23077:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b64a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3
23087:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=xba --oflag=s8s8_comp:1 --attr-oscale=per_dim_1:3 32x32x3
23088:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=xba --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:3 32x32x3
23089:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=xba --oflag=s8s8_comp:1 --attr-oscale=per_tensor:0.7 32x32x3
23093:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=xba --oflag=zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3
23094:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=xba --oflag=zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3
23095:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=xba --oflag=zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3
23099:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=xba --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3
23100:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=xba --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3
23101:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=xba --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3
23111:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx2b8a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_1:3 32x32x3
23112:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx2b8a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:3 32x32x3
23113:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx2b8a4b --oflag=s8s8_comp:1 --attr-oscale=per_tensor:0.7 32x32x3
23117:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx2b8a4b --oflag=zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3
23118:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx2b8a4b --oflag=zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3
23119:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx2b8a4b --oflag=zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3
23123:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx2b8a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3
23124:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx2b8a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3
23125:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx2b8a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3
23135:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_1:3 32x32x3
23136:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:3 32x32x3
23137:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4a4b --oflag=s8s8_comp:1 --attr-oscale=per_tensor:0.7 32x32x3
23141:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4a4b --oflag=zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3
23142:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4a4b --oflag=zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3
23143:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4a4b --oflag=zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3
23147:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3
23148:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3
23149:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3
23159:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b16a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_1:3 32x32x3
23160:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b16a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:3 32x32x3
23161:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b16a4b --oflag=s8s8_comp:1 --attr-oscale=per_tensor:0.7 32x32x3
23165:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b16a4b --oflag=zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3
23166:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b16a4b --oflag=zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3
23167:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b16a4b --oflag=zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3
23171:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b16a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3
23172:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b16a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3
23173:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b16a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3
23183:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b32a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_1:3 32x32x3
23184:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b32a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:3 32x32x3
23185:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b32a4b --oflag=s8s8_comp:1 --attr-oscale=per_tensor:0.7 32x32x3
23189:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b32a4b --oflag=zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3
23190:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b32a4b --oflag=zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3
23191:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b32a4b --oflag=zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3
23195:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b32a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3
23196:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b32a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3
23197:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b32a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3
23207:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b64a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_1:3 32x32x3
23208:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b64a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:3 32x32x3
23209:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b64a4b --oflag=s8s8_comp:1 --attr-oscale=per_tensor:0.7 32x32x3
23213:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b64a4b --oflag=zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3
23214:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b64a4b --oflag=zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3
23215:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b64a4b --oflag=zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3
23219:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b64a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3
23220:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b64a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3
23221:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b64a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3
23231:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=xba --oflag=s8s8_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3
23232:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=xba --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3
23233:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=xba --oflag=s8s8_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3
23237:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=xba --oflag=zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3
23238:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=xba --oflag=zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3
23239:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=xba --oflag=zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3
23243:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=xba --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3
23244:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=xba --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3
23245:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=xba --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3
23255:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx2b8a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3
23256:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx2b8a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3
23257:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx2b8a4b --oflag=s8s8_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3
23261:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx2b8a4b --oflag=zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3
23262:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx2b8a4b --oflag=zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3
23263:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx2b8a4b --oflag=zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3
23267:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx2b8a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3
23268:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx2b8a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3
23269:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx2b8a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3
23279:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3
23280:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3
23281:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4a4b --oflag=s8s8_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3
23285:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4a4b --oflag=zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3
23286:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4a4b --oflag=zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3
23287:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4a4b --oflag=zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3
23291:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3
23292:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3
23293:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3
23303:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b16a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3
23304:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b16a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3
23305:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b16a4b --oflag=s8s8_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3
23309:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b16a4b --oflag=zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3
23310:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b16a4b --oflag=zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3
23311:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b16a4b --oflag=zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3
23315:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b16a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3
23316:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b16a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3
23317:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b16a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3
23327:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b32a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3
23328:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b32a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3
23329:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b32a4b --oflag=s8s8_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3
23333:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b32a4b --oflag=zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3
23334:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b32a4b --oflag=zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3
23335:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b32a4b --oflag=zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3
23339:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b32a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3
23340:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b32a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3
23341:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b32a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3
23351:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b64a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3
23352:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b64a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3
23353:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b64a4b --oflag=s8s8_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3
23357:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b64a4b --oflag=zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3
23358:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b64a4b --oflag=zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3
23359:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b64a4b --oflag=zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3
23363:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b64a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3
23364:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b64a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3
23365:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b64a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3
23375:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=xba --oflag=s8s8_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3
23376:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=xba --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3
23377:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=xba --oflag=s8s8_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3
23381:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=xba --oflag=zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3
23382:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=xba --oflag=zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3
23383:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=xba --oflag=zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3
23387:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=xba --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3
23388:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=xba --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3
23389:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=xba --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3
23399:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx2b8a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3
23400:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx2b8a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3
23401:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx2b8a4b --oflag=s8s8_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3
23405:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx2b8a4b --oflag=zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3
23406:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx2b8a4b --oflag=zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3
23407:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx2b8a4b --oflag=zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3
23411:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx2b8a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3
23412:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx2b8a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3
23413:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx2b8a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3
23423:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3
23424:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3
23425:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4a4b --oflag=s8s8_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3
23429:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4a4b --oflag=zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3
23430:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4a4b --oflag=zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3
23431:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4a4b --oflag=zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3
23435:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3
23436:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3
23437:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3
23447:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b16a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3
23448:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b16a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3
23449:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b16a4b --oflag=s8s8_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3
23453:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b16a4b --oflag=zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3
23454:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b16a4b --oflag=zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3
23455:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b16a4b --oflag=zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3
23459:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b16a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3
23460:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b16a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3
23461:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b16a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3
23471:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b32a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3
23472:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b32a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3
23473:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b32a4b --oflag=s8s8_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3
23477:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b32a4b --oflag=zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3
23478:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b32a4b --oflag=zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3
23479:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b32a4b --oflag=zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3
23483:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b32a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3
23484:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b32a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3
23485:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b32a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3
23495:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b64a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3
23496:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b64a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3
23497:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b64a4b --oflag=s8s8_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3
23501:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b64a4b --oflag=zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3
23502:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b64a4b --oflag=zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3
23503:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b64a4b --oflag=zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3
23507:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b64a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3
23508:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b64a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3
23509:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b64a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3
23519:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=xba --oflag=s8s8_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3
23520:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=xba --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3
23521:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=xba --oflag=s8s8_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3
23525:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=xba --oflag=zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3
23526:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=xba --oflag=zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3
23527:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=xba --oflag=zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3
23531:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=xba --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3
23532:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=xba --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3
23533:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=xba --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3
23543:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx2b8a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3
23544:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx2b8a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3
23545:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx2b8a4b --oflag=s8s8_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3
23549:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx2b8a4b --oflag=zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3
23550:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx2b8a4b --oflag=zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3
23551:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx2b8a4b --oflag=zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3
23555:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx2b8a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3
23556:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx2b8a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3
23557:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx2b8a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3
23567:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3
23568:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3
23569:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4a4b --oflag=s8s8_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3
23573:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4a4b --oflag=zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3
23574:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4a4b --oflag=zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3
23575:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4a4b --oflag=zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3
23579:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3
23580:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3
23581:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3
23591:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b16a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3
23592:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b16a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3
23593:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b16a4b --oflag=s8s8_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3
23597:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b16a4b --oflag=zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3
23598:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b16a4b --oflag=zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3
23599:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b16a4b --oflag=zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3
23603:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b16a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3
23604:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b16a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3
23605:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b16a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3
23615:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b32a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3
23616:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b32a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3
23617:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b32a4b --oflag=s8s8_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3
23621:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b32a4b --oflag=zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3
23622:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b32a4b --oflag=zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3
23623:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b32a4b --oflag=zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3
23627:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b32a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3
23628:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b32a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3
23629:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b32a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3
23639:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b64a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3
23640:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b64a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3
23641:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b64a4b --oflag=s8s8_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3
23645:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b64a4b --oflag=zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3
23646:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b64a4b --oflag=zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3
23647:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b64a4b --oflag=zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3
23651:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b64a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3
23652:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b64a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3
23653:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b64a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3
23663:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=xba --oflag=s8s8_comp:1 --attr-oscale=per_dim_1:3 80x24x3x5
23664:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=xba --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:3 80x24x3x5
23665:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=xba --oflag=s8s8_comp:1 --attr-oscale=per_tensor:0.7 80x24x3x5
23669:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=xba --oflag=zp_comp:1 --attr-oscale=per_dim_1:3 80x24x3x5
23670:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=xba --oflag=zp_comp:1 --attr-oscale=per_dim_01:3 80x24x3x5
23671:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=xba --oflag=zp_comp:1 --attr-oscale=per_tensor:0.7 80x24x3x5
23675:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=xba --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_1:3 80x24x3x5
23676:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=xba --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:3 80x24x3x5
23677:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=xba --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_tensor:0.7 80x24x3x5
23687:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx2b8a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_1:3 80x24x3x5
23688:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx2b8a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:3 80x24x3x5
23689:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx2b8a4b --oflag=s8s8_comp:1 --attr-oscale=per_tensor:0.7 80x24x3x5
23693:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx2b8a4b --oflag=zp_comp:1 --attr-oscale=per_dim_1:3 80x24x3x5
23694:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx2b8a4b --oflag=zp_comp:1 --attr-oscale=per_dim_01:3 80x24x3x5
23695:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx2b8a4b --oflag=zp_comp:1 --attr-oscale=per_tensor:0.7 80x24x3x5
23699:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx2b8a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_1:3 80x24x3x5
23700:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx2b8a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:3 80x24x3x5
23701:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx2b8a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_tensor:0.7 80x24x3x5
23711:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_1:3 80x24x3x5
23712:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:3 80x24x3x5
23713:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4a4b --oflag=s8s8_comp:1 --attr-oscale=per_tensor:0.7 80x24x3x5
23717:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4a4b --oflag=zp_comp:1 --attr-oscale=per_dim_1:3 80x24x3x5
23718:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4a4b --oflag=zp_comp:1 --attr-oscale=per_dim_01:3 80x24x3x5
23719:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4a4b --oflag=zp_comp:1 --attr-oscale=per_tensor:0.7 80x24x3x5
23723:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_1:3 80x24x3x5
23724:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:3 80x24x3x5
23725:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_tensor:0.7 80x24x3x5
23735:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b16a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_1:3 80x24x3x5
23736:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b16a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:3 80x24x3x5
23737:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b16a4b --oflag=s8s8_comp:1 --attr-oscale=per_tensor:0.7 80x24x3x5
23741:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b16a4b --oflag=zp_comp:1 --attr-oscale=per_dim_1:3 80x24x3x5
23742:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b16a4b --oflag=zp_comp:1 --attr-oscale=per_dim_01:3 80x24x3x5
23743:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b16a4b --oflag=zp_comp:1 --attr-oscale=per_tensor:0.7 80x24x3x5
23747:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b16a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_1:3 80x24x3x5
23748:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b16a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:3 80x24x3x5
23749:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b16a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_tensor:0.7 80x24x3x5
23759:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b32a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_1:3 80x24x3x5
23760:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b32a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:3 80x24x3x5
23761:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b32a4b --oflag=s8s8_comp:1 --attr-oscale=per_tensor:0.7 80x24x3x5
23765:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b32a4b --oflag=zp_comp:1 --attr-oscale=per_dim_1:3 80x24x3x5
23766:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b32a4b --oflag=zp_comp:1 --attr-oscale=per_dim_01:3 80x24x3x5
23767:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b32a4b --oflag=zp_comp:1 --attr-oscale=per_tensor:0.7 80x24x3x5
23771:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b32a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_1:3 80x24x3x5
23772:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b32a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:3 80x24x3x5
23773:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b32a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_tensor:0.7 80x24x3x5
23783:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b64a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_1:3 80x24x3x5
23784:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b64a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:3 80x24x3x5
23785:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b64a4b --oflag=s8s8_comp:1 --attr-oscale=per_tensor:0.7 80x24x3x5
23789:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b64a4b --oflag=zp_comp:1 --attr-oscale=per_dim_1:3 80x24x3x5
23790:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b64a4b --oflag=zp_comp:1 --attr-oscale=per_dim_01:3 80x24x3x5
23791:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b64a4b --oflag=zp_comp:1 --attr-oscale=per_tensor:0.7 80x24x3x5
23795:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b64a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_1:3 80x24x3x5
23796:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b64a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:3 80x24x3x5
23797:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b64a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_tensor:0.7 80x24x3x5
23807:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=xba --oflag=s8s8_comp:1 --attr-oscale=per_dim_1:3 80x24x3x5
23808:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=xba --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:3 80x24x3x5
23809:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=xba --oflag=s8s8_comp:1 --attr-oscale=per_tensor:0.7 80x24x3x5
23813:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=xba --oflag=zp_comp:1 --attr-oscale=per_dim_1:3 80x24x3x5
23814:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=xba --oflag=zp_comp:1 --attr-oscale=per_dim_01:3 80x24x3x5
23815:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=xba --oflag=zp_comp:1 --attr-oscale=per_tensor:0.7 80x24x3x5
23819:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=xba --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_1:3 80x24x3x5
23820:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=xba --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:3 80x24x3x5
23821:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=xba --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_tensor:0.7 80x24x3x5
23831:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx2b8a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_1:3 80x24x3x5
23832:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx2b8a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:3 80x24x3x5
23833:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx2b8a4b --oflag=s8s8_comp:1 --attr-oscale=per_tensor:0.7 80x24x3x5
23837:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx2b8a4b --oflag=zp_comp:1 --attr-oscale=per_dim_1:3 80x24x3x5
23838:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx2b8a4b --oflag=zp_comp:1 --attr-oscale=per_dim_01:3 80x24x3x5
23839:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx2b8a4b --oflag=zp_comp:1 --attr-oscale=per_tensor:0.7 80x24x3x5
23843:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx2b8a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_1:3 80x24x3x5
23844:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx2b8a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:3 80x24x3x5
23845:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx2b8a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_tensor:0.7 80x24x3x5
23855:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_1:3 80x24x3x5
23856:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:3 80x24x3x5
23857:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4a4b --oflag=s8s8_comp:1 --attr-oscale=per_tensor:0.7 80x24x3x5
23861:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4a4b --oflag=zp_comp:1 --attr-oscale=per_dim_1:3 80x24x3x5
23862:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4a4b --oflag=zp_comp:1 --attr-oscale=per_dim_01:3 80x24x3x5
23863:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4a4b --oflag=zp_comp:1 --attr-oscale=per_tensor:0.7 80x24x3x5
23867:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_1:3 80x24x3x5
23868:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:3 80x24x3x5
23869:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_tensor:0.7 80x24x3x5
23879:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b16a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_1:3 80x24x3x5
23880:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b16a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:3 80x24x3x5
23881:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b16a4b --oflag=s8s8_comp:1 --attr-oscale=per_tensor:0.7 80x24x3x5
23885:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b16a4b --oflag=zp_comp:1 --attr-oscale=per_dim_1:3 80x24x3x5
23886:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b16a4b --oflag=zp_comp:1 --attr-oscale=per_dim_01:3 80x24x3x5
23887:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b16a4b --oflag=zp_comp:1 --attr-oscale=per_tensor:0.7 80x24x3x5
23891:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b16a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_1:3 80x24x3x5
23892:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b16a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:3 80x24x3x5
23893:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b16a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_tensor:0.7 80x24x3x5
23903:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b32a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_1:3 80x24x3x5
23904:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b32a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:3 80x24x3x5
23905:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b32a4b --oflag=s8s8_comp:1 --attr-oscale=per_tensor:0.7 80x24x3x5
23909:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b32a4b --oflag=zp_comp:1 --attr-oscale=per_dim_1:3 80x24x3x5
23910:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b32a4b --oflag=zp_comp:1 --attr-oscale=per_dim_01:3 80x24x3x5
23911:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b32a4b --oflag=zp_comp:1 --attr-oscale=per_tensor:0.7 80x24x3x5
23915:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b32a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_1:3 80x24x3x5
23916:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b32a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:3 80x24x3x5
23917:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b32a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_tensor:0.7 80x24x3x5
23927:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b64a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_1:3 80x24x3x5
23928:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b64a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:3 80x24x3x5
23929:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b64a4b --oflag=s8s8_comp:1 --attr-oscale=per_tensor:0.7 80x24x3x5
23933:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b64a4b --oflag=zp_comp:1 --attr-oscale=per_dim_1:3 80x24x3x5
23934:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b64a4b --oflag=zp_comp:1 --attr-oscale=per_dim_01:3 80x24x3x5
23935:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b64a4b --oflag=zp_comp:1 --attr-oscale=per_tensor:0.7 80x24x3x5
23939:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b64a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_1:3 80x24x3x5
23940:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b64a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:3 80x24x3x5
23941:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b64a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_tensor:0.7 80x24x3x5
23951:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=xba --oflag=s8s8_comp:1 --attr-oscale=per_dim_1:3 80x24x3x5
23952:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=xba --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:3 80x24x3x5
23953:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=xba --oflag=s8s8_comp:1 --attr-oscale=per_tensor:0.7 80x24x3x5
23957:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=xba --oflag=zp_comp:1 --attr-oscale=per_dim_1:3 80x24x3x5
23958:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=xba --oflag=zp_comp:1 --attr-oscale=per_dim_01:3 80x24x3x5
23959:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=xba --oflag=zp_comp:1 --attr-oscale=per_tensor:0.7 80x24x3x5
23963:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=xba --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_1:3 80x24x3x5
23964:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=xba --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:3 80x24x3x5
23965:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=xba --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_tensor:0.7 80x24x3x5
23975:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx2b8a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_1:3 80x24x3x5
23976:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx2b8a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:3 80x24x3x5
23977:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx2b8a4b --oflag=s8s8_comp:1 --attr-oscale=per_tensor:0.7 80x24x3x5
23981:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx2b8a4b --oflag=zp_comp:1 --attr-oscale=per_dim_1:3 80x24x3x5
23982:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx2b8a4b --oflag=zp_comp:1 --attr-oscale=per_dim_01:3 80x24x3x5
23983:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx2b8a4b --oflag=zp_comp:1 --attr-oscale=per_tensor:0.7 80x24x3x5
23987:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx2b8a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_1:3 80x24x3x5
23988:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx2b8a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:3 80x24x3x5
23989:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx2b8a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_tensor:0.7 80x24x3x5
23999:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_1:3 80x24x3x5
24000:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:3 80x24x3x5
24001:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4a4b --oflag=s8s8_comp:1 --attr-oscale=per_tensor:0.7 80x24x3x5
24005:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4a4b --oflag=zp_comp:1 --attr-oscale=per_dim_1:3 80x24x3x5
24006:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4a4b --oflag=zp_comp:1 --attr-oscale=per_dim_01:3 80x24x3x5
24007:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4a4b --oflag=zp_comp:1 --attr-oscale=per_tensor:0.7 80x24x3x5
24011:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_1:3 80x24x3x5
24012:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:3 80x24x3x5
24013:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_tensor:0.7 80x24x3x5
24023:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b16a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_1:3 80x24x3x5
24024:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b16a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:3 80x24x3x5
24025:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b16a4b --oflag=s8s8_comp:1 --attr-oscale=per_tensor:0.7 80x24x3x5
24029:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b16a4b --oflag=zp_comp:1 --attr-oscale=per_dim_1:3 80x24x3x5
24030:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b16a4b --oflag=zp_comp:1 --attr-oscale=per_dim_01:3 80x24x3x5
24031:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b16a4b --oflag=zp_comp:1 --attr-oscale=per_tensor:0.7 80x24x3x5
24035:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b16a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_1:3 80x24x3x5
24036:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b16a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:3 80x24x3x5
24037:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b16a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_tensor:0.7 80x24x3x5
24047:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b32a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_1:3 80x24x3x5
24048:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b32a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:3 80x24x3x5
24049:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b32a4b --oflag=s8s8_comp:1 --attr-oscale=per_tensor:0.7 80x24x3x5
24053:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b32a4b --oflag=zp_comp:1 --attr-oscale=per_dim_1:3 80x24x3x5
24054:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b32a4b --oflag=zp_comp:1 --attr-oscale=per_dim_01:3 80x24x3x5
24055:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b32a4b --oflag=zp_comp:1 --attr-oscale=per_tensor:0.7 80x24x3x5
24059:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b32a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_1:3 80x24x3x5
24060:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b32a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:3 80x24x3x5
24061:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b32a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_tensor:0.7 80x24x3x5
24071:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b64a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_1:3 80x24x3x5
24072:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b64a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:3 80x24x3x5
24073:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b64a4b --oflag=s8s8_comp:1 --attr-oscale=per_tensor:0.7 80x24x3x5
24077:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b64a4b --oflag=zp_comp:1 --attr-oscale=per_dim_1:3 80x24x3x5
24078:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b64a4b --oflag=zp_comp:1 --attr-oscale=per_dim_01:3 80x24x3x5
24079:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b64a4b --oflag=zp_comp:1 --attr-oscale=per_tensor:0.7 80x24x3x5
24083:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b64a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_1:3 80x24x3x5
24084:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b64a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:3 80x24x3x5
24085:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b64a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_tensor:0.7 80x24x3x5
24095:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=xba --oflag=s8s8_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3x3
24096:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=xba --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3x3
24097:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=xba --oflag=s8s8_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3x3
24101:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=xba --oflag=zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3x3
24102:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=xba --oflag=zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3x3
24103:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=xba --oflag=zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3x3
24107:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=xba --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3x3
24108:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=xba --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3x3
24109:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=xba --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3x3
24119:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx2b8a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3x3
24120:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx2b8a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3x3
24121:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx2b8a4b --oflag=s8s8_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3x3
24125:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx2b8a4b --oflag=zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3x3
24126:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx2b8a4b --oflag=zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3x3
24127:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx2b8a4b --oflag=zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3x3
24131:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx2b8a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3x3
24132:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx2b8a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3x3
24133:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx2b8a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3x3
24143:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3x3
24144:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3x3
24145:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4a4b --oflag=s8s8_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3x3
24149:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4a4b --oflag=zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3x3
24150:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4a4b --oflag=zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3x3
24151:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4a4b --oflag=zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3x3
24155:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3x3
24156:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3x3
24157:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3x3
24167:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b16a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3x3
24168:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b16a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3x3
24169:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b16a4b --oflag=s8s8_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3x3
24173:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b16a4b --oflag=zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3x3
24174:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b16a4b --oflag=zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3x3
24175:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b16a4b --oflag=zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3x3
24179:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b16a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3x3
24180:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b16a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3x3
24181:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b16a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3x3
24191:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b32a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3x3
24192:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b32a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3x3
24193:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b32a4b --oflag=s8s8_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3x3
24197:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b32a4b --oflag=zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3x3
24198:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b32a4b --oflag=zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3x3
24199:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b32a4b --oflag=zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3x3
24203:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b32a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3x3
24204:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b32a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3x3
24205:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b32a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3x3
24215:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b64a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3x3
24216:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b64a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3x3
24217:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b64a4b --oflag=s8s8_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3x3
24221:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b64a4b --oflag=zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3x3
24222:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b64a4b --oflag=zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3x3
24223:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b64a4b --oflag=zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3x3
24227:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b64a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3x3
24228:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b64a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3x3
24229:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b64a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3x3
24239:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=xba --oflag=s8s8_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3x3
24240:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=xba --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3x3
24241:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=xba --oflag=s8s8_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3x3
24245:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=xba --oflag=zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3x3
24246:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=xba --oflag=zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3x3
24247:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=xba --oflag=zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3x3
24251:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=xba --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3x3
24252:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=xba --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3x3
24253:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=xba --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3x3
24263:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx2b8a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3x3
24264:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx2b8a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3x3
24265:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx2b8a4b --oflag=s8s8_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3x3
24269:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx2b8a4b --oflag=zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3x3
24270:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx2b8a4b --oflag=zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3x3
24271:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx2b8a4b --oflag=zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3x3
24275:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx2b8a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3x3
24276:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx2b8a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3x3
24277:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx2b8a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3x3
24287:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3x3
24288:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3x3
24289:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4a4b --oflag=s8s8_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3x3
24293:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4a4b --oflag=zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3x3
24294:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4a4b --oflag=zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3x3
24295:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4a4b --oflag=zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3x3
24299:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3x3
24300:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3x3
24301:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3x3
24311:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b16a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3x3
24312:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b16a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3x3
24313:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b16a4b --oflag=s8s8_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3x3
24317:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b16a4b --oflag=zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3x3
24318:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b16a4b --oflag=zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3x3
24319:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b16a4b --oflag=zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3x3
24323:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b16a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3x3
24324:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b16a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3x3
24325:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b16a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3x3
24335:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b32a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3x3
24336:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b32a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3x3
24337:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b32a4b --oflag=s8s8_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3x3
24341:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b32a4b --oflag=zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3x3
24342:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b32a4b --oflag=zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3x3
24343:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b32a4b --oflag=zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3x3
24347:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b32a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3x3
24348:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b32a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3x3
24349:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b32a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3x3
24359:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b64a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3x3
24360:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b64a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3x3
24361:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b64a4b --oflag=s8s8_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3x3
24365:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b64a4b --oflag=zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3x3
24366:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b64a4b --oflag=zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3x3
24367:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b64a4b --oflag=zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3x3
24371:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b64a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3x3
24372:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b64a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3x3
24373:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABx4b64a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3x3
24383:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=xba --oflag=s8s8_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3x3
24384:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=xba --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3x3
24385:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=xba --oflag=s8s8_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3x3
24389:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=xba --oflag=zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3x3
24390:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=xba --oflag=zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3x3
24391:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=xba --oflag=zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3x3
24395:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=xba --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3x3
24396:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=xba --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3x3
24397:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=xba --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3x3
24407:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx2b8a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3x3
24408:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx2b8a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3x3
24409:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx2b8a4b --oflag=s8s8_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3x3
24413:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx2b8a4b --oflag=zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3x3
24414:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx2b8a4b --oflag=zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3x3
24415:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx2b8a4b --oflag=zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3x3
24419:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx2b8a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3x3
24420:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx2b8a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3x3
24421:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx2b8a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3x3
24431:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3x3
24432:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3x3
24433:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4a4b --oflag=s8s8_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3x3
24437:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4a4b --oflag=zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3x3
24438:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4a4b --oflag=zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3x3
24439:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4a4b --oflag=zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3x3
24443:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3x3
24444:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3x3
24445:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3x3
24455:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b16a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3x3
24456:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b16a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3x3
24457:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b16a4b --oflag=s8s8_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3x3
24461:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b16a4b --oflag=zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3x3
24462:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b16a4b --oflag=zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3x3
24463:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b16a4b --oflag=zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3x3
24467:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b16a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3x3
24468:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b16a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3x3
24469:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b16a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3x3
24479:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b32a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3x3
24480:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b32a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3x3
24481:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b32a4b --oflag=s8s8_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3x3
24485:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b32a4b --oflag=zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3x3
24486:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b32a4b --oflag=zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3x3
24487:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b32a4b --oflag=zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3x3
24491:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b32a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3x3
24492:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b32a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3x3
24493:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b32a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3x3
24503:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b64a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3x3
24504:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b64a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3x3
24505:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b64a4b --oflag=s8s8_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3x3
24509:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b64a4b --oflag=zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3x3
24510:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b64a4b --oflag=zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3x3
24511:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b64a4b --oflag=zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3x3
24515:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b64a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3x3x3
24516:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b64a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3x3x3
24517:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABx4b64a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3x3x3
25887:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABc2b8a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:1 4x4x1
25888:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABc2b8a4b --oflag=zp_comp:1 --attr-oscale=per_dim_01:1 4x4x1
25889:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABc2b8a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:1 4x4x1
25891:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABc2b8a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:1 4x4x1
25892:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABc2b8a4b --oflag=zp_comp:1 --attr-oscale=per_dim_01:1 4x4x1
25893:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xba --dtag=ABc2b8a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:1 4x4x1
25895:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABc2b8a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:1 4x4x1
25896:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABc2b8a4b --oflag=zp_comp:1 --attr-oscale=per_dim_01:1 4x4x1
25897:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=bxa --dtag=ABc2b8a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:1 4x4x1
25899:SKIPPED (DATA_TYPE_NOT_SUPPORTED) __REPRO: --reorder --sdt=bf16 --ddt=s8 --stag=abx --dtag=ABc2b8a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:1 4x4x1
25900:SKIPPED (DATA_TYPE_NOT_SUPPORTED) __REPRO: --reorder --sdt=bf16 --ddt=s8 --stag=abx --dtag=ABc2b8a4b --oflag=zp_comp:1 --attr-oscale=per_dim_01:1 4x4x1
25901:SKIPPED (DATA_TYPE_NOT_SUPPORTED) __REPRO: --reorder --sdt=bf16 --ddt=s8 --stag=abx --dtag=ABc2b8a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:1 4x4x1
25903:SKIPPED (DATA_TYPE_NOT_SUPPORTED) __REPRO: --reorder --sdt=bf16 --ddt=s8 --stag=xba --dtag=ABc2b8a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:1 4x4x1
25904:SKIPPED (DATA_TYPE_NOT_SUPPORTED) __REPRO: --reorder --sdt=bf16 --ddt=s8 --stag=xba --dtag=ABc2b8a4b --oflag=zp_comp:1 --attr-oscale=per_dim_01:1 4x4x1
25905:SKIPPED (DATA_TYPE_NOT_SUPPORTED) __REPRO: --reorder --sdt=bf16 --ddt=s8 --stag=xba --dtag=ABc2b8a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:1 4x4x1
25907:SKIPPED (DATA_TYPE_NOT_SUPPORTED) __REPRO: --reorder --sdt=bf16 --ddt=s8 --stag=bxa --dtag=ABc2b8a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:1 4x4x1
25908:SKIPPED (DATA_TYPE_NOT_SUPPORTED) __REPRO: --reorder --sdt=bf16 --ddt=s8 --stag=bxa --dtag=ABc2b8a4b --oflag=zp_comp:1 --attr-oscale=per_dim_01:1 4x4x1
25909:SKIPPED (DATA_TYPE_NOT_SUPPORTED) __REPRO: --reorder --sdt=bf16 --ddt=s8 --stag=bxa --dtag=ABc2b8a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:1 4x4x1
25911:UNIMPLEMENTED __REPRO: --reorder --sdt=s8 --ddt=s8 --stag=abx --dtag=ABc2b8a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:1 4x4x1
25912:UNIMPLEMENTED __REPRO: --reorder --sdt=s8 --ddt=s8 --stag=abx --dtag=ABc2b8a4b --oflag=zp_comp:1 --attr-oscale=per_dim_01:1 4x4x1
25913:UNIMPLEMENTED __REPRO: --reorder --sdt=s8 --ddt=s8 --stag=abx --dtag=ABc2b8a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:1 4x4x1
25915:UNIMPLEMENTED __REPRO: --reorder --sdt=s8 --ddt=s8 --stag=xba --dtag=ABc2b8a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:1 4x4x1
25916:UNIMPLEMENTED __REPRO: --reorder --sdt=s8 --ddt=s8 --stag=xba --dtag=ABc2b8a4b --oflag=zp_comp:1 --attr-oscale=per_dim_01:1 4x4x1
25917:UNIMPLEMENTED __REPRO: --reorder --sdt=s8 --ddt=s8 --stag=xba --dtag=ABc2b8a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:1 4x4x1
25919:UNIMPLEMENTED __REPRO: --reorder --sdt=s8 --ddt=s8 --stag=bxa --dtag=ABc2b8a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:1 4x4x1
25920:UNIMPLEMENTED __REPRO: --reorder --sdt=s8 --ddt=s8 --stag=bxa --dtag=ABc2b8a4b --oflag=zp_comp:1 --attr-oscale=per_dim_01:1 4x4x1
25921:UNIMPLEMENTED __REPRO: --reorder --sdt=s8 --ddt=s8 --stag=bxa --dtag=ABc2b8a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:1 4x4x1
[  69][1:34] exp_f32:  -28800 exp:  -28800 got:  -28801 diff:       1 rdiff:3.47222e-05
26404:FAILED (errors:1 total:70) __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=aBCx4b4c --oflag=s8s8_comp:3 2x35x35x3x3
[  69][1:34] exp_f32:  -57600 exp:  -57600 got:  -57601 diff:       1 rdiff:1.73611e-05
26405:FAILED (errors:1 total:70) __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=aBCx4b4c --oflag=s8s8_comp:3 --attr-oscale=common:2 2x35x35x3x3
[  69][1:34] exp_f32:    -225 exp:    -225 got:    -226 diff:       1 rdiff:0.00444444
26406:FAILED (errors:1 total:70) __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=aBCx4b4c --oflag=zp_comp:3 2x35x35x3x3
[  69][1:34] exp_f32:    -450 exp:    -450 got:    -451 diff:       1 rdiff:0.00222222
26407:FAILED (errors:1 total:70) __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=aBCx4b4c --oflag=zp_comp:3 --attr-oscale=common:2 2x35x35x3x3
[  69][1:34] exp_f32:  -28800 exp:  -28800 got:  -28801 diff:       1 rdiff:3.47222e-05
26408:FAILED (errors:1 total:70) __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=aBCx4b4c --oflag=s8s8_comp:3+zp_comp:3 2x35x35x3x3
[  69][1:34] exp_f32:  -57600 exp:  -57600 got:  -57601 diff:       1 rdiff:1.73611e-05
26409:FAILED (errors:1 total:70) __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=aBCx4b4c --oflag=s8s8_comp:3+zp_comp:3 --attr-oscale=common:2 2x35x35x3x3
[  69][1:34] exp_f32:  -28800 exp:  -28800 got:  -28801 diff:       1 rdiff:3.47222e-05
26412:FAILED (errors:1 total:70) __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xcab --dtag=aBCx4b4c --oflag=s8s8_comp:3 2x35x35x3x3
[  69][1:34] exp_f32:  -57600 exp:  -57600 got:  -57601 diff:       1 rdiff:1.73611e-05
26413:FAILED (errors:1 total:70) __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xcab --dtag=aBCx4b4c --oflag=s8s8_comp:3 --attr-oscale=common:2 2x35x35x3x3
[  69][1:34] exp_f32:    -225 exp:    -225 got:    -226 diff:       1 rdiff:0.00444444
26414:FAILED (errors:1 total:70) __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xcab --dtag=aBCx4b4c --oflag=zp_comp:3 2x35x35x3x3
[  69][1:34] exp_f32:    -450 exp:    -450 got:    -451 diff:       1 rdiff:0.00222222
26415:FAILED (errors:1 total:70) __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xcab --dtag=aBCx4b4c --oflag=zp_comp:3 --attr-oscale=common:2 2x35x35x3x3
[  69][1:34] exp_f32:  -28800 exp:  -28800 got:  -28801 diff:       1 rdiff:3.47222e-05
26416:FAILED (errors:1 total:70) __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xcab --dtag=aBCx4b4c --oflag=s8s8_comp:3+zp_comp:3 2x35x35x3x3
[  69][1:34] exp_f32:  -57600 exp:  -57600 got:  -57601 diff:       1 rdiff:1.73611e-05
26417:FAILED (errors:1 total:70) __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xcab --dtag=aBCx4b4c --oflag=s8s8_comp:3+zp_comp:3 --attr-oscale=common:2 2x35x35x3x3
[  69][1:34] exp_f32:  -28800 exp:  -28800 got:  -28801 diff:       1 rdiff:3.47222e-05
26420:FAILED (errors:1 total:70) __REPRO: --reorder --sdt=bf16 --ddt=s8 --stag=abx --dtag=aBCx4b4c --oflag=s8s8_comp:3 2x35x35x3x3
[  69][1:34] exp_f32:  -57600 exp:  -57600 got:  -57601 diff:       1 rdiff:1.73611e-05
26421:FAILED (errors:1 total:70) __REPRO: --reorder --sdt=bf16 --ddt=s8 --stag=abx --dtag=aBCx4b4c --oflag=s8s8_comp:3 --attr-oscale=common:2 2x35x35x3x3
[  69][1:34] exp_f32:    -225 exp:    -225 got:    -226 diff:       1 rdiff:0.00444444
26422:FAILED (errors:1 total:70) __REPRO: --reorder --sdt=bf16 --ddt=s8 --stag=abx --dtag=aBCx4b4c --oflag=zp_comp:3 2x35x35x3x3
[  69][1:34] exp_f32:    -450 exp:    -450 got:    -451 diff:       1 rdiff:0.00222222
26423:FAILED (errors:1 total:70) __REPRO: --reorder --sdt=bf16 --ddt=s8 --stag=abx --dtag=aBCx4b4c --oflag=zp_comp:3 --attr-oscale=common:2 2x35x35x3x3
[  69][1:34] exp_f32:  -28800 exp:  -28800 got:  -28801 diff:       1 rdiff:3.47222e-05
26424:FAILED (errors:1 total:70) __REPRO: --reorder --sdt=bf16 --ddt=s8 --stag=abx --dtag=aBCx4b4c --oflag=s8s8_comp:3+zp_comp:3 2x35x35x3x3
[  69][1:34] exp_f32:  -57600 exp:  -57600 got:  -57601 diff:       1 rdiff:1.73611e-05
26425:FAILED (errors:1 total:70) __REPRO: --reorder --sdt=bf16 --ddt=s8 --stag=abx --dtag=aBCx4b4c --oflag=s8s8_comp:3+zp_comp:3 --attr-oscale=common:2 2x35x35x3x3
[  69][1:34] exp_f32:  -28800 exp:  -28800 got:  -28801 diff:       1 rdiff:3.47222e-05
26428:FAILED (errors:1 total:70) __REPRO: --reorder --sdt=bf16 --ddt=s8 --stag=xcab --dtag=aBCx4b4c --oflag=s8s8_comp:3 2x35x35x3x3
[  69][1:34] exp_f32:  -57600 exp:  -57600 got:  -57601 diff:       1 rdiff:1.73611e-05
26429:FAILED (errors:1 total:70) __REPRO: --reorder --sdt=bf16 --ddt=s8 --stag=xcab --dtag=aBCx4b4c --oflag=s8s8_comp:3 --attr-oscale=common:2 2x35x35x3x3
[  69][1:34] exp_f32:    -225 exp:    -225 got:    -226 diff:       1 rdiff:0.00444444
26430:FAILED (errors:1 total:70) __REPRO: --reorder --sdt=bf16 --ddt=s8 --stag=xcab --dtag=aBCx4b4c --oflag=zp_comp:3 2x35x35x3x3
[  69][1:34] exp_f32:    -450 exp:    -450 got:    -451 diff:       1 rdiff:0.00222222
26431:FAILED (errors:1 total:70) __REPRO: --reorder --sdt=bf16 --ddt=s8 --stag=xcab --dtag=aBCx4b4c --oflag=zp_comp:3 --attr-oscale=common:2 2x35x35x3x3
[  69][1:34] exp_f32:  -28800 exp:  -28800 got:  -28801 diff:       1 rdiff:3.47222e-05
26432:FAILED (errors:1 total:70) __REPRO: --reorder --sdt=bf16 --ddt=s8 --stag=xcab --dtag=aBCx4b4c --oflag=s8s8_comp:3+zp_comp:3 2x35x35x3x3
[  69][1:34] exp_f32:  -57600 exp:  -57600 got:  -57601 diff:       1 rdiff:1.73611e-05
26433:FAILED (errors:1 total:70) __REPRO: --reorder --sdt=bf16 --ddt=s8 --stag=xcab --dtag=aBCx4b4c --oflag=s8s8_comp:3+zp_comp:3 --attr-oscale=common:2 2x35x35x3x3
[  69][1:34] exp_f32: -151680 exp: -151680 got: -151681 diff:       1 rdiff:6.59283e-06
26436:FAILED (errors:1 total:70) __REPRO: --reorder --sdt=s8 --ddt=s8 --stag=abx --dtag=aBCx4b4c --oflag=s8s8_comp:3 2x35x35x3x3
[  69][1:34] exp_f32: -313472 exp: -313472 got: -313473 diff:       1 rdiff:3.19008e-06
26437:FAILED (errors:1 total:70) __REPRO: --reorder --sdt=s8 --ddt=s8 --stag=abx --dtag=aBCx4b4c --oflag=s8s8_comp:3 --attr-oscale=common:2 2x35x35x3x3
[  69][1:34] exp_f32:   -1185 exp:   -1185 got:   -1186 diff:       1 rdiff:0.000843882
26438:FAILED (errors:1 total:70) __REPRO: --reorder --sdt=s8 --ddt=s8 --stag=abx --dtag=aBCx4b4c --oflag=zp_comp:3 2x35x35x3x3
[  69][1:34] exp_f32:   -2449 exp:   -2449 got:   -2450 diff:       1 rdiff:0.00040833
26439:FAILED (errors:1 total:70) __REPRO: --reorder --sdt=s8 --ddt=s8 --stag=abx --dtag=aBCx4b4c --oflag=zp_comp:3 --attr-oscale=common:2 2x35x35x3x3
[  69][1:34] exp_f32: -151680 exp: -151680 got: -151681 diff:       1 rdiff:6.59283e-06
26440:FAILED (errors:1 total:70) __REPRO: --reorder --sdt=s8 --ddt=s8 --stag=abx --dtag=aBCx4b4c --oflag=s8s8_comp:3+zp_comp:3 2x35x35x3x3
[  69][1:34] exp_f32: -313472 exp: -313472 got: -313473 diff:       1 rdiff:3.19008e-06
26441:FAILED (errors:1 total:70) __REPRO: --reorder --sdt=s8 --ddt=s8 --stag=abx --dtag=aBCx4b4c --oflag=s8s8_comp:3+zp_comp:3 --attr-oscale=common:2 2x35x35x3x3
[  69][1:34] exp_f32: -151680 exp: -151680 got: -151681 diff:       1 rdiff:6.59283e-06
26444:FAILED (errors:1 total:70) __REPRO: --reorder --sdt=s8 --ddt=s8 --stag=xcab --dtag=aBCx4b4c --oflag=s8s8_comp:3 2x35x35x3x3
[  69][1:34] exp_f32: -313472 exp: -313472 got: -313473 diff:       1 rdiff:3.19008e-06
26445:FAILED (errors:1 total:70) __REPRO: --reorder --sdt=s8 --ddt=s8 --stag=xcab --dtag=aBCx4b4c --oflag=s8s8_comp:3 --attr-oscale=common:2 2x35x35x3x3
[  69][1:34] exp_f32:   -1185 exp:   -1185 got:   -1186 diff:       1 rdiff:0.000843882
26446:FAILED (errors:1 total:70) __REPRO: --reorder --sdt=s8 --ddt=s8 --stag=xcab --dtag=aBCx4b4c --oflag=zp_comp:3 2x35x35x3x3
[  69][1:34] exp_f32:   -2449 exp:   -2449 got:   -2450 diff:       1 rdiff:0.00040833
26447:FAILED (errors:1 total:70) __REPRO: --reorder --sdt=s8 --ddt=s8 --stag=xcab --dtag=aBCx4b4c --oflag=zp_comp:3 --attr-oscale=common:2 2x35x35x3x3
[  69][1:34] exp_f32: -151680 exp: -151680 got: -151681 diff:       1 rdiff:6.59283e-06
26448:FAILED (errors:1 total:70) __REPRO: --reorder --sdt=s8 --ddt=s8 --stag=xcab --dtag=aBCx4b4c --oflag=s8s8_comp:3+zp_comp:3 2x35x35x3x3
[  69][1:34] exp_f32: -313472 exp: -313472 got: -313473 diff:       1 rdiff:3.19008e-06
26449:FAILED (errors:1 total:70) __REPRO: --reorder --sdt=s8 --ddt=s8 --stag=xcab --dtag=aBCx4b4c --oflag=s8s8_comp:3+zp_comp:3 --attr-oscale=common:2 2x35x35x3x3
26836:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=Abcx16a --oflag=s8s8_comp:3 3x2x2x3
26837:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=Abcx16a --oflag=s8s8_comp:3 --attr-oscale=common:2 3x2x2x3
26838:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=Abcx16a --oflag=zp_comp:3 3x2x2x3
26839:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=Abcx16a --oflag=zp_comp:3 --attr-oscale=common:2 3x2x2x3
26840:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=Abcx16a --oflag=s8s8_comp:3+zp_comp:3 3x2x2x3
26841:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=Abcx16a --oflag=s8s8_comp:3+zp_comp:3 --attr-oscale=common:2 3x2x2x3
26844:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=Abcx8a --oflag=s8s8_comp:3 3x2x2x3
26845:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=Abcx8a --oflag=s8s8_comp:3 --attr-oscale=common:2 3x2x2x3
26846:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=Abcx8a --oflag=zp_comp:3 3x2x2x3
26847:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=Abcx8a --oflag=zp_comp:3 --attr-oscale=common:2 3x2x2x3
26848:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=Abcx8a --oflag=s8s8_comp:3+zp_comp:3 3x2x2x3
26849:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=Abcx8a --oflag=s8s8_comp:3+zp_comp:3 --attr-oscale=common:2 3x2x2x3
26852:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=Abcx4a --oflag=s8s8_comp:3 3x2x2x3
26853:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=Abcx4a --oflag=s8s8_comp:3 --attr-oscale=common:2 3x2x2x3
26854:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=Abcx4a --oflag=zp_comp:3 3x2x2x3
26855:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=Abcx4a --oflag=zp_comp:3 --attr-oscale=common:2 3x2x2x3
26856:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=Abcx4a --oflag=s8s8_comp:3+zp_comp:3 3x2x2x3
26857:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=Abcx4a --oflag=s8s8_comp:3+zp_comp:3 --attr-oscale=common:2 3x2x2x3
26860:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xcab --dtag=Abcx16a --oflag=s8s8_comp:3 3x2x2x3
26861:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xcab --dtag=Abcx16a --oflag=s8s8_comp:3 --attr-oscale=common:2 3x2x2x3
26862:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xcab --dtag=Abcx16a --oflag=zp_comp:3 3x2x2x3
26863:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xcab --dtag=Abcx16a --oflag=zp_comp:3 --attr-oscale=common:2 3x2x2x3
26864:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xcab --dtag=Abcx16a --oflag=s8s8_comp:3+zp_comp:3 3x2x2x3
26865:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xcab --dtag=Abcx16a --oflag=s8s8_comp:3+zp_comp:3 --attr-oscale=common:2 3x2x2x3
26868:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xcab --dtag=Abcx8a --oflag=s8s8_comp:3 3x2x2x3
26869:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xcab --dtag=Abcx8a --oflag=s8s8_comp:3 --attr-oscale=common:2 3x2x2x3
26870:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xcab --dtag=Abcx8a --oflag=zp_comp:3 3x2x2x3
26871:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xcab --dtag=Abcx8a --oflag=zp_comp:3 --attr-oscale=common:2 3x2x2x3
26872:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xcab --dtag=Abcx8a --oflag=s8s8_comp:3+zp_comp:3 3x2x2x3
26873:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xcab --dtag=Abcx8a --oflag=s8s8_comp:3+zp_comp:3 --attr-oscale=common:2 3x2x2x3
26876:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xcab --dtag=Abcx4a --oflag=s8s8_comp:3 3x2x2x3
26877:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xcab --dtag=Abcx4a --oflag=s8s8_comp:3 --attr-oscale=common:2 3x2x2x3
26878:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xcab --dtag=Abcx4a --oflag=zp_comp:3 3x2x2x3
26879:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xcab --dtag=Abcx4a --oflag=zp_comp:3 --attr-oscale=common:2 3x2x2x3
26880:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xcab --dtag=Abcx4a --oflag=s8s8_comp:3+zp_comp:3 3x2x2x3
26881:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=xcab --dtag=Abcx4a --oflag=s8s8_comp:3+zp_comp:3 --attr-oscale=common:2 3x2x2x3
26884:SKIPPED (DATA_TYPE_NOT_SUPPORTED) __REPRO: --reorder --sdt=bf16 --ddt=s8 --stag=abx --dtag=Abcx16a --oflag=s8s8_comp:3 3x2x2x3
26885:SKIPPED (DATA_TYPE_NOT_SUPPORTED) __REPRO: --reorder --sdt=bf16 --ddt=s8 --stag=abx --dtag=Abcx16a --oflag=s8s8_comp:3 --attr-oscale=common:2 3x2x2x3
26886:SKIPPED (DATA_TYPE_NOT_SUPPORTED) __REPRO: --reorder --sdt=bf16 --ddt=s8 --stag=abx --dtag=Abcx16a --oflag=zp_comp:3 3x2x2x3
26887:SKIPPED (DATA_TYPE_NOT_SUPPORTED) __REPRO: --reorder --sdt=bf16 --ddt=s8 --stag=abx --dtag=Abcx16a --oflag=zp_comp:3 --attr-oscale=common:2 3x2x2x3
26888:SKIPPED (DATA_TYPE_NOT_SUPPORTED) __REPRO: --reorder --sdt=bf16 --ddt=s8 --stag=abx --dtag=Abcx16a --oflag=s8s8_comp:3+zp_comp:3 3x2x2x3
26889:SKIPPED (DATA_TYPE_NOT_SUPPORTED) __REPRO: --reorder --sdt=bf16 --ddt=s8 --stag=abx --dtag=Abcx16a --oflag=s8s8_comp:3+zp_comp:3 --attr-oscale=common:2 3x2x2x3
26892:SKIPPED (DATA_TYPE_NOT_SUPPORTED) __REPRO: --reorder --sdt=bf16 --ddt=s8 --stag=abx --dtag=Abcx8a --oflag=s8s8_comp:3 3x2x2x3
26893:SKIPPED (DATA_TYPE_NOT_SUPPORTED) __REPRO: --reorder --sdt=bf16 --ddt=s8 --stag=abx --dtag=Abcx8a --oflag=s8s8_comp:3 --attr-oscale=common:2 3x2x2x3
26894:SKIPPED (DATA_TYPE_NOT_SUPPORTED) __REPRO: --reorder --sdt=bf16 --ddt=s8 --stag=abx --dtag=Abcx8a --oflag=zp_comp:3 3x2x2x3
26895:SKIPPED (DATA_TYPE_NOT_SUPPORTED) __REPRO: --reorder --sdt=bf16 --ddt=s8 --stag=abx --dtag=Abcx8a --oflag=zp_comp:3 --attr-oscale=common:2 3x2x2x3
26896:SKIPPED (DATA_TYPE_NOT_SUPPORTED) __REPRO: --reorder --sdt=bf16 --ddt=s8 --stag=abx --dtag=Abcx8a --oflag=s8s8_comp:3+zp_comp:3 3x2x2x3
26897:SKIPPED (DATA_TYPE_NOT_SUPPORTED) __REPRO: --reorder --sdt=bf16 --ddt=s8 --stag=abx --dtag=Abcx8a --oflag=s8s8_comp:3+zp_comp:3 --attr-oscale=common:2 3x2x2x3
26900:SKIPPED (DATA_TYPE_NOT_SUPPORTED) __REPRO: --reorder --sdt=bf16 --ddt=s8 --stag=abx --dtag=Abcx4a --oflag=s8s8_comp:3 3x2x2x3
26901:SKIPPED (DATA_TYPE_NOT_SUPPORTED) __REPRO: --reorder --sdt=bf16 --ddt=s8 --stag=abx --dtag=Abcx4a --oflag=s8s8_comp:3 --attr-oscale=common:2 3x2x2x3
26902:SKIPPED (DATA_TYPE_NOT_SUPPORTED) __REPRO: --reorder --sdt=bf16 --ddt=s8 --stag=abx --dtag=Abcx4a --oflag=zp_comp:3 3x2x2x3
26903:SKIPPED (DATA_TYPE_NOT_SUPPORTED) __REPRO: --reorder --sdt=bf16 --ddt=s8 --stag=abx --dtag=Abcx4a --oflag=zp_comp:3 --attr-oscale=common:2 3x2x2x3
26904:SKIPPED (DATA_TYPE_NOT_SUPPORTED) __REPRO: --reorder --sdt=bf16 --ddt=s8 --stag=abx --dtag=Abcx4a --oflag=s8s8_comp:3+zp_comp:3 3x2x2x3
26905:SKIPPED (DATA_TYPE_NOT_SUPPORTED) __REPRO: --reorder --sdt=bf16 --ddt=s8 --stag=abx --dtag=Abcx4a --oflag=s8s8_comp:3+zp_comp:3 --attr-oscale=common:2 3x2x2x3
26908:SKIPPED (DATA_TYPE_NOT_SUPPORTED) __REPRO: --reorder --sdt=bf16 --ddt=s8 --stag=xcab --dtag=Abcx16a --oflag=s8s8_comp:3 3x2x2x3
26909:SKIPPED (DATA_TYPE_NOT_SUPPORTED) __REPRO: --reorder --sdt=bf16 --ddt=s8 --stag=xcab --dtag=Abcx16a --oflag=s8s8_comp:3 --attr-oscale=common:2 3x2x2x3
26910:SKIPPED (DATA_TYPE_NOT_SUPPORTED) __REPRO: --reorder --sdt=bf16 --ddt=s8 --stag=xcab --dtag=Abcx16a --oflag=zp_comp:3 3x2x2x3
26911:SKIPPED (DATA_TYPE_NOT_SUPPORTED) __REPRO: --reorder --sdt=bf16 --ddt=s8 --stag=xcab --dtag=Abcx16a --oflag=zp_comp:3 --attr-oscale=common:2 3x2x2x3
26912:SKIPPED (DATA_TYPE_NOT_SUPPORTED) __REPRO: --reorder --sdt=bf16 --ddt=s8 --stag=xcab --dtag=Abcx16a --oflag=s8s8_comp:3+zp_comp:3 3x2x2x3
26913:SKIPPED (DATA_TYPE_NOT_SUPPORTED) __REPRO: --reorder --sdt=bf16 --ddt=s8 --stag=xcab --dtag=Abcx16a --oflag=s8s8_comp:3+zp_comp:3 --attr-oscale=common:2 3x2x2x3
26916:SKIPPED (DATA_TYPE_NOT_SUPPORTED) __REPRO: --reorder --sdt=bf16 --ddt=s8 --stag=xcab --dtag=Abcx8a --oflag=s8s8_comp:3 3x2x2x3
26917:SKIPPED (DATA_TYPE_NOT_SUPPORTED) __REPRO: --reorder --sdt=bf16 --ddt=s8 --stag=xcab --dtag=Abcx8a --oflag=s8s8_comp:3 --attr-oscale=common:2 3x2x2x3
26918:SKIPPED (DATA_TYPE_NOT_SUPPORTED) __REPRO: --reorder --sdt=bf16 --ddt=s8 --stag=xcab --dtag=Abcx8a --oflag=zp_comp:3 3x2x2x3
26919:SKIPPED (DATA_TYPE_NOT_SUPPORTED) __REPRO: --reorder --sdt=bf16 --ddt=s8 --stag=xcab --dtag=Abcx8a --oflag=zp_comp:3 --attr-oscale=common:2 3x2x2x3
26920:SKIPPED (DATA_TYPE_NOT_SUPPORTED) __REPRO: --reorder --sdt=bf16 --ddt=s8 --stag=xcab --dtag=Abcx8a --oflag=s8s8_comp:3+zp_comp:3 3x2x2x3
26921:SKIPPED (DATA_TYPE_NOT_SUPPORTED) __REPRO: --reorder --sdt=bf16 --ddt=s8 --stag=xcab --dtag=Abcx8a --oflag=s8s8_comp:3+zp_comp:3 --attr-oscale=common:2 3x2x2x3
26924:SKIPPED (DATA_TYPE_NOT_SUPPORTED) __REPRO: --reorder --sdt=bf16 --ddt=s8 --stag=xcab --dtag=Abcx4a --oflag=s8s8_comp:3 3x2x2x3
26925:SKIPPED (DATA_TYPE_NOT_SUPPORTED) __REPRO: --reorder --sdt=bf16 --ddt=s8 --stag=xcab --dtag=Abcx4a --oflag=s8s8_comp:3 --attr-oscale=common:2 3x2x2x3
26926:SKIPPED (DATA_TYPE_NOT_SUPPORTED) __REPRO: --reorder --sdt=bf16 --ddt=s8 --stag=xcab --dtag=Abcx4a --oflag=zp_comp:3 3x2x2x3
26927:SKIPPED (DATA_TYPE_NOT_SUPPORTED) __REPRO: --reorder --sdt=bf16 --ddt=s8 --stag=xcab --dtag=Abcx4a --oflag=zp_comp:3 --attr-oscale=common:2 3x2x2x3
26928:SKIPPED (DATA_TYPE_NOT_SUPPORTED) __REPRO: --reorder --sdt=bf16 --ddt=s8 --stag=xcab --dtag=Abcx4a --oflag=s8s8_comp:3+zp_comp:3 3x2x2x3
26929:SKIPPED (DATA_TYPE_NOT_SUPPORTED) __REPRO: --reorder --sdt=bf16 --ddt=s8 --stag=xcab --dtag=Abcx4a --oflag=s8s8_comp:3+zp_comp:3 --attr-oscale=common:2 3x2x2x3
26932:UNIMPLEMENTED __REPRO: --reorder --sdt=s8 --ddt=s8 --stag=abx --dtag=Abcx16a --oflag=s8s8_comp:3 3x2x2x3
26933:UNIMPLEMENTED __REPRO: --reorder --sdt=s8 --ddt=s8 --stag=abx --dtag=Abcx16a --oflag=s8s8_comp:3 --attr-oscale=common:2 3x2x2x3
26934:UNIMPLEMENTED __REPRO: --reorder --sdt=s8 --ddt=s8 --stag=abx --dtag=Abcx16a --oflag=zp_comp:3 3x2x2x3
26935:UNIMPLEMENTED __REPRO: --reorder --sdt=s8 --ddt=s8 --stag=abx --dtag=Abcx16a --oflag=zp_comp:3 --attr-oscale=common:2 3x2x2x3
26936:UNIMPLEMENTED __REPRO: --reorder --sdt=s8 --ddt=s8 --stag=abx --dtag=Abcx16a --oflag=s8s8_comp:3+zp_comp:3 3x2x2x3
26937:UNIMPLEMENTED __REPRO: --reorder --sdt=s8 --ddt=s8 --stag=abx --dtag=Abcx16a --oflag=s8s8_comp:3+zp_comp:3 --attr-oscale=common:2 3x2x2x3
26940:UNIMPLEMENTED __REPRO: --reorder --sdt=s8 --ddt=s8 --stag=abx --dtag=Abcx8a --oflag=s8s8_comp:3 3x2x2x3
26941:UNIMPLEMENTED __REPRO: --reorder --sdt=s8 --ddt=s8 --stag=abx --dtag=Abcx8a --oflag=s8s8_comp:3 --attr-oscale=common:2 3x2x2x3
26942:UNIMPLEMENTED __REPRO: --reorder --sdt=s8 --ddt=s8 --stag=abx --dtag=Abcx8a --oflag=zp_comp:3 3x2x2x3
26943:UNIMPLEMENTED __REPRO: --reorder --sdt=s8 --ddt=s8 --stag=abx --dtag=Abcx8a --oflag=zp_comp:3 --attr-oscale=common:2 3x2x2x3
26944:UNIMPLEMENTED __REPRO: --reorder --sdt=s8 --ddt=s8 --stag=abx --dtag=Abcx8a --oflag=s8s8_comp:3+zp_comp:3 3x2x2x3
26945:UNIMPLEMENTED __REPRO: --reorder --sdt=s8 --ddt=s8 --stag=abx --dtag=Abcx8a --oflag=s8s8_comp:3+zp_comp:3 --attr-oscale=common:2 3x2x2x3
26948:UNIMPLEMENTED __REPRO: --reorder --sdt=s8 --ddt=s8 --stag=abx --dtag=Abcx4a --oflag=s8s8_comp:3 3x2x2x3
26949:UNIMPLEMENTED __REPRO: --reorder --sdt=s8 --ddt=s8 --stag=abx --dtag=Abcx4a --oflag=s8s8_comp:3 --attr-oscale=common:2 3x2x2x3
26950:UNIMPLEMENTED __REPRO: --reorder --sdt=s8 --ddt=s8 --stag=abx --dtag=Abcx4a --oflag=zp_comp:3 3x2x2x3
26951:UNIMPLEMENTED __REPRO: --reorder --sdt=s8 --ddt=s8 --stag=abx --dtag=Abcx4a --oflag=zp_comp:3 --attr-oscale=common:2 3x2x2x3
26952:UNIMPLEMENTED __REPRO: --reorder --sdt=s8 --ddt=s8 --stag=abx --dtag=Abcx4a --oflag=s8s8_comp:3+zp_comp:3 3x2x2x3
26953:UNIMPLEMENTED __REPRO: --reorder --sdt=s8 --ddt=s8 --stag=abx --dtag=Abcx4a --oflag=s8s8_comp:3+zp_comp:3 --attr-oscale=common:2 3x2x2x3
26956:UNIMPLEMENTED __REPRO: --reorder --sdt=s8 --ddt=s8 --stag=xcab --dtag=Abcx16a --oflag=s8s8_comp:3 3x2x2x3
26957:UNIMPLEMENTED __REPRO: --reorder --sdt=s8 --ddt=s8 --stag=xcab --dtag=Abcx16a --oflag=s8s8_comp:3 --attr-oscale=common:2 3x2x2x3
26958:UNIMPLEMENTED __REPRO: --reorder --sdt=s8 --ddt=s8 --stag=xcab --dtag=Abcx16a --oflag=zp_comp:3 3x2x2x3
26959:UNIMPLEMENTED __REPRO: --reorder --sdt=s8 --ddt=s8 --stag=xcab --dtag=Abcx16a --oflag=zp_comp:3 --attr-oscale=common:2 3x2x2x3
26960:UNIMPLEMENTED __REPRO: --reorder --sdt=s8 --ddt=s8 --stag=xcab --dtag=Abcx16a --oflag=s8s8_comp:3+zp_comp:3 3x2x2x3
26961:UNIMPLEMENTED __REPRO: --reorder --sdt=s8 --ddt=s8 --stag=xcab --dtag=Abcx16a --oflag=s8s8_comp:3+zp_comp:3 --attr-oscale=common:2 3x2x2x3
26964:UNIMPLEMENTED __REPRO: --reorder --sdt=s8 --ddt=s8 --stag=xcab --dtag=Abcx8a --oflag=s8s8_comp:3 3x2x2x3
26965:UNIMPLEMENTED __REPRO: --reorder --sdt=s8 --ddt=s8 --stag=xcab --dtag=Abcx8a --oflag=s8s8_comp:3 --attr-oscale=common:2 3x2x2x3
26966:UNIMPLEMENTED __REPRO: --reorder --sdt=s8 --ddt=s8 --stag=xcab --dtag=Abcx8a --oflag=zp_comp:3 3x2x2x3
26967:UNIMPLEMENTED __REPRO: --reorder --sdt=s8 --ddt=s8 --stag=xcab --dtag=Abcx8a --oflag=zp_comp:3 --attr-oscale=common:2 3x2x2x3
26968:UNIMPLEMENTED __REPRO: --reorder --sdt=s8 --ddt=s8 --stag=xcab --dtag=Abcx8a --oflag=s8s8_comp:3+zp_comp:3 3x2x2x3
26969:UNIMPLEMENTED __REPRO: --reorder --sdt=s8 --ddt=s8 --stag=xcab --dtag=Abcx8a --oflag=s8s8_comp:3+zp_comp:3 --attr-oscale=common:2 3x2x2x3
26972:UNIMPLEMENTED __REPRO: --reorder --sdt=s8 --ddt=s8 --stag=xcab --dtag=Abcx4a --oflag=s8s8_comp:3 3x2x2x3
26973:UNIMPLEMENTED __REPRO: --reorder --sdt=s8 --ddt=s8 --stag=xcab --dtag=Abcx4a --oflag=s8s8_comp:3 --attr-oscale=common:2 3x2x2x3
26974:UNIMPLEMENTED __REPRO: --reorder --sdt=s8 --ddt=s8 --stag=xcab --dtag=Abcx4a --oflag=zp_comp:3 3x2x2x3
26975:UNIMPLEMENTED __REPRO: --reorder --sdt=s8 --ddt=s8 --stag=xcab --dtag=Abcx4a --oflag=zp_comp:3 --attr-oscale=common:2 3x2x2x3
26976:UNIMPLEMENTED __REPRO: --reorder --sdt=s8 --ddt=s8 --stag=xcab --dtag=Abcx4a --oflag=s8s8_comp:3+zp_comp:3 3x2x2x3
26977:UNIMPLEMENTED __REPRO: --reorder --sdt=s8 --ddt=s8 --stag=xcab --dtag=Abcx4a --oflag=s8s8_comp:3+zp_comp:3 --attr-oscale=common:2 3x2x2x3
tests:27194 passed:26373 skipped:47 mistrusted:0 unimplemented:738 invalid_arguments:0 failed:774 listed:0
total compute_ref: sum(s):5.58
```

The verbose log of the first FAILED pattern (26404-th pattern of `test_reorder_all`). Arm requires compensation when u8s8 instead of s8s8, is that relevant?
```
DNNL_VERBOSE=2 ./benchdnn --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=aBCx4b4c --oflag=s8s8_comp:3 2x35x35x3x3
onednn_verbose,info,oneDNN v2.6.0 (commit 04be459dcb1a14745d83f5159e26f545c0648ab7)
onednn_verbose,info,cpu,runtime:OpenMP,nthr:48
onednn_verbose,info,cpu,isa:AArch64 SVE (512 bits)
onednn_verbose,info,gpu,runtime:none
onednn_verbose,info,prim_template:operation,engine,primitive,implementation,prop_kind,memory_descriptors,attributes,auxiliary,problem_desc,exec_time
onednn_verbose,create:cache_miss,cpu,reorder,simple:any,undef,src_f32::blocked:abcde:f0 dst_s8:p:blocked:aBCde4b4c:f1:s8m3,,,2x35x35x3x3,0.0610352
onednn_verbose,create:cache_hit,cpu,reorder,simple:any,undef,src_f32::blocked:abcde:f0 dst_s8:p:blocked:aBCde4b4c:f1:s8m3,,,2x35x35x3x3,0.00708008
onednn_verbose,create:cache_miss,cpu,reorder,simple:any,undef,src_f32::blocked:abcde:f0 dst_f32::blocked:abcde:f0,,,2x35x35x3x3,0.0239258
onednn_verbose,exec,cpu,reorder,simple:any,undef,src_f32::blocked:abcde:f0 dst_f32::blocked:abcde:f0,,,2x35x35x3x3,3.09106
onednn_verbose,exec,cpu,reorder,simple:any,undef,src_f32::blocked:abcde:f0 dst_s8:p:blocked:aBCde4b4c:f1:s8m3,,,2x35x35x3x3,3.34204
onednn_verbose,create:cache_miss,cpu,reorder,simple:any,undef,src_s8:p:blocked:aBCde4b4c:f0 dst_f32::blocked:abcde:f0,,,2x35x35x3x3,0.0251465
onednn_verbose,exec,cpu,reorder,simple:any,undef,src_s8:p:blocked:aBCde4b4c:f0 dst_f32::blocked:abcde:f0,,,2x35x35x3x3,0.800049
onednn_verbose,create:cache_miss,cpu,reorder,simple:any,undef,src_s32:p:blocked:aB4b:f0 dst_f32::blocked:ab:f0,,,2x35,0.0180664
onednn_verbose,exec,cpu,reorder,simple:any,undef,src_s32:p:blocked:aB4b:f0 dst_f32::blocked:ab:f0,,,2x35,0.666016
[  69][1:34] exp_f32:  -28800 exp:  -28800 got:  -28801 diff:       1 rdiff:3.47222e-05
@@@ error [int reorder::compare_compensation(const reorder::prb_t*, dnn_mem_t&, dnn_mem_t&, dnn_mem_t&, res_t*):145]: 'cmp_compensation(mem_s8_comp_ref, prb->get_compensation_mask(FLAG_S8S8_COMP))' -> 1
0:FAILED (errors:1 total:70) __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=aBCx4b4c --oflag=s8s8_comp:3 2x35x35x3x3
tests:1 passed:0 skipped:0 mistrusted:0 unimplemented:0 invalid_arguments:0 failed:1 listed:0
total compute_ref: sum(s):0.00
```

**Comment by igorsafo** [comment]
Hi @kawakami-k , thanks for the testing, indeed there was an issue with initializing compensation memory. I fixed it, please try again.

File: src/cpu/reorder/simple_reorder.hpp (hunk 3 above)
Comment (igorsafo) [reply src/cpu/reorder/simple_reorder.hpp:384]: Discussed offline. API-level changes will require a lot of work, while only couple of implementations are affected by the current behavior. Desicion is to keep it as is.

**Comment by igorsafo** [comment]
@kawakami-k There is an issue related to sve512 convolution, that also affects `master` branch. Are you aware about that issue?

**Comment by kawakami-k** [comment]
@igorsafo 

> @kawakami-k There is an issue related to sve512 convolution, that also affects `master` branch. Are you aware about that issue?

Thank you. I am aware of it. https://cloud.drone.io/oneapi-src/oneDNN/1276/7/2

**Comment by kawakami-k** [comment]
@igorsafo 

Thank you for updating simple_reorder.

./benchdnn --reorder --batch=test_reorder_ci | tail -n 2
tests:18150 passed:8742 skipped:9408 mistrusted:0 unimplemented:0 invalid_arguments:0 failed:0 listed:0
total compute_ref: sum(s):1.64

./benchdnn --reorder --batch=test_reorder_all | tail -n 2
tests:27194 passed:26409 skipped:47 mistrusted:0 unimplemented:738 invalid_arguments:0 failed:738 listed:0
total compute_ref: sum(s):18.30

./benchdnn --reorder --batch=test_reorder_all | grep UNIMPLEMENTED | head -n 30
22799:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=xba --oflag=s8s8_comp:1 --attr-oscale=per_dim_1:3 32x32x3
22800:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=xba --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:3 32x32x3
22801:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=xba --oflag=s8s8_comp:1 --attr-oscale=per_tensor:0.7 32x32x3
22805:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=xba --oflag=zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3
22806:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=xba --oflag=zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3
22807:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=xba --oflag=zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3
22811:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=xba --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3
22812:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=xba --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3
22813:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=xba --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3
22823:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx2b8a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_1:3 32x32x3
22824:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx2b8a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:3 32x32x3
22825:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx2b8a4b --oflag=s8s8_comp:1 --attr-oscale=per_tensor:0.7 32x32x3
22829:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx2b8a4b --oflag=zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3
22830:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx2b8a4b --oflag=zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3
22831:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx2b8a4b --oflag=zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3
22835:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx2b8a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3
22836:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx2b8a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3
22837:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx2b8a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3
22847:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_1:3 32x32x3
22848:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:3 32x32x3
22849:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4a4b --oflag=s8s8_comp:1 --attr-oscale=per_tensor:0.7 32x32x3
22853:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4a4b --oflag=zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3
22854:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4a4b --oflag=zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3
22855:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4a4b --oflag=zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3
22859:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_1:3 32x32x3
22860:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_dim_01:3 32x32x3
22861:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4a4b --oflag=s8s8_comp:1+zp_comp:1 --attr-oscale=per_tensor:0.7 32x32x3
22871:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b16a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_1:3 32x32x3
22872:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b16a4b --oflag=s8s8_comp:1 --attr-oscale=per_dim_01:3 32x32x3
22873:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=ABx4b16a4b --oflag=s8s8_comp:1 --attr-oscale=per_tensor:0.7 32x32x3

`22799-th test pattern of test_reorder_all`
DNNL_VERBOSE=2 ./benchdnn --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=xba --oflag=s8s8_comp:1 --attr-oscale=per_dim_1:3 32x32x3
@@@ error [int init_prim(benchdnn_dnnl_wrapper_t<dnnl_primitive*>&, const func_t&, prb_t*, res_t*, dir_t, const_dnnl_primitive_desc_t) [with func_t = dnnl_status_t(dnnl_engine*, const reorder::prb_t*, dnnl_primitive_desc*&, res_t*, dir_t, const dnnl_primitive_desc*); prb_t = const reorder::prb_t; const_dnnl_primitive_desc_t = const dnnl_primitive_desc*]:461]: 'check_dnnl_status(status, prb, res)' -> 1
@@@ error [int reorder::doit(const reorder::prb_t*, res_t*):289]: 'init_prim(prim, init_pd, prb, res)' -> 1
0:UNIMPLEMENTED __REPRO: --reorder --sdt=f32 --ddt=s8 --stag=abx --dtag=xba --oflag=s8s8_comp:1 --attr-oscale=per_dim_1:3 32x32x3
tests:1 passed:0 skipped:0 mistrusted:0 unimplemented:1 invalid_arguments:0 failed:1 listed:0
total compute_ref: sum(s):0.00

The other `UNIMPLEMENTED` patterns also producde the same message `@@@ error [int reorder::doit(const reorder::prb_t*, res_t*):289]: 'init_prim(prim, init_pd, prb, res)' -> 1`.

**Comment by igorsafo** [comment]
@kawakami-k Thanks for the update!
I am aware of the unimplemented reorder cases, this is caused by a combination of `s8s8_comp` oscale mask `per_dim_1` which is not supported by reference reorders. I think the test case is invalid, because `s8s8_comp` is a feature for weights, when we need to precompute some values to make a convolution faster. Weights dimensions order is `[OC, IC, H, W]`, so `per_dim_1` is actually a per `IC` output scale which doesn't make sense. I will try to modify input files so there is no intersection of these 2 flags.

**Comment by igorsafo** [comment]
@kawakami-k I extended the reference reorder and added a check into benchdnn to skip some output scale policies if platform is not x64. Now all tests pass for batch file `test_reorder_all` on qemu-aarch64 with sve512.

@dzarukin Could you please review again?

File: tests/benchdnn/reorder/reorder.cpp [hunk 4]
```diff
@@ -195,6 +196,20 @@ void skip_unimplemented_prb(const prb_t *prb, res_t *res) {
     skip_unimplemented_data_type({sdt, ddt}, prb->dir, res);
     skip_unimplemented_sum_po(prb->attr, res);
 
+    bool oscale_ok = true;
+#if !defined(DNNL_X64) || DNNL_X64 == 0
+    {
+        // reference reorder supports only a subset of oscale policies
+        oscale_ok = dnnl::impl::utils::one_of(prb->attr.oscale.policy,
```
Comment (dzarukin) [inline tests/benchdnn/reorder/reorder.cpp:203]: Please use [std::any_of](https://github.com/oneapi-src/oneDNN/blob/master/tests/benchdnn/binary/binary.cpp#L162) instead.

**Review by dzarukin — APPROVED** [review]

File: tests/benchdnn/reorder/reorder.cpp (hunk 4 above)
Comment (igorsafo) [reply tests/benchdnn/reorder/reorder.cpp]: thanks, done.
